export type KleioPageGuide = {
  title: string
  role: "artist" | "institution" | "collaborator"
  description: string
  benefit: string
  realWorld: string
}

type GuideRow = [
  path: string,
  title: string,
  role: KleioPageGuide["role"],
  description: string,
  benefit: string,
  realWorld: string,
  titleEs: string,
  descriptionEs: string,
  benefitEs: string,
  realWorldEs: string,
]

const rows: GuideRow[] = [
  ["/signup/artist/", "Artist Signup", "artist", "This page starts the artist setup flow.", "It helps the artist begin a reusable profile with basic identity, practice, links, and materials context.", "This is the first step toward reducing repeated application setup across grants, residencies, exhibitions, and open calls.", "Registro de artista", "Esta página inicia el flujo de configuración para artistas.", "Ayuda al artista a comenzar un perfil reutilizable con identidad, práctica, enlaces y contexto de materiales.", "Es el primer paso para reducir la repetición administrativa entre becas, residencias, exposiciones y convocatorias."],
  ["/signup/institution/", "Institution Signup", "institution", "This page starts the institution workspace setup.", "It helps the organization define who they are, what kinds of programs they manage, and how review should begin.", "This gives the review process a structure before submissions, reviewers, and decisions start spreading across separate tools.", "Registro institucional", "Esta página inicia la configuración del espacio institucional.", "Ayuda a la organización a definir quién es, qué programas maneja y cómo debe comenzar la revisión.", "Le da estructura al proceso antes de que postulaciones, revisores y decisiones se dispersen entre herramientas separadas."],
  ["/dashboard/", "Overview", "institution", "This page gives the institution a shared view of the current review cycle.", "It helps the team see status, deadlines, materials, progress, and decision timing before opening individual records.", "Use it like the first page of a review meeting: where are we, what is behind schedule, and what needs attention today?", "Resumen", "Esta página le da a la institución una vista compartida del ciclo de revisión actual.", "Ayuda al equipo a ver estado, fechas, materiales, progreso y tiempos de decisión antes de abrir registros individuales.", "Úsala como la primera página de una reunión de revisión: dónde estamos, qué va atrasado y qué necesita atención hoy."],
  ["/programs/", "Programs & Open Calls", "institution", "This page keeps grants, residencies, exhibitions, and open calls organized as programs.", "It helps the institution see each program's status, deadline, submission count, required materials, and review progress.", "This gives active calls one clear board instead of scattered intake folders.", "Programas y convocatorias", "Esta página mantiene becas, residencias, exposiciones y convocatorias organizadas como programas.", "Ayuda a ver el estado, fecha límite, número de postulaciones, materiales requeridos y progreso de revisión de cada programa.", "Le da a las convocatorias activas un tablero claro en vez de carpetas dispersas."],
  ["/programs/new/", "New Program Draft", "institution", "This page shapes a new open call, grant, residency, or exhibition intake flow.", "It helps define eligibility, deadlines, required materials, questions, and review stages before submissions arrive.", "A clear intake structure gives artists clearer instructions and gives reviewers cleaner information later.", "Nuevo borrador de programa", "Esta página da forma a una nueva convocatoria, beca, residencia o flujo de recepción para exposición.", "Ayuda a definir elegibilidad, fechas, materiales requeridos, preguntas y etapas de revisión antes de recibir postulaciones.", "Una estructura clara da mejores instrucciones a artistas y mejor información a revisores."],
  ["/submissions/", "Submissions", "institution", "This is the searchable record of artist submissions across active programs.", "It helps staff find artists, compare submissions, check material status, and keep context close to each record.", "For teams used to inboxes, PDFs, and spreadsheets, this becomes the organized record of what was received.", "Postulaciones", "Este es el registro buscable de postulaciones artísticas en programas activos.", "Ayuda al equipo a encontrar artistas, comparar postulaciones, revisar materiales y mantener el contexto cerca de cada registro.", "Para equipos acostumbrados a correos, PDFs y hojas de cálculo, esto se vuelve el registro organizado de lo recibido."],
  ["/artists/", "Artist Records", "institution", "This page keeps artist records connected to submissions and program history.", "It helps the institution understand an applicant beyond a single uploaded file.", "It keeps artist materials from becoming disconnected attachments with no memory between review cycles.", "Registros de artistas", "Esta página mantiene registros de artistas conectados a postulaciones e historial de programas.", "Ayuda a entender a una persona postulante más allá de un solo archivo subido.", "Evita que los materiales artísticos se conviertan en adjuntos desconectados sin memoria entre ciclos de revisión."],
  ["/review-queue/", "Review Queue", "institution", "This page organizes submissions that need review, follow-up, or committee attention.", "It brings readiness, priority, reviewer assignment, deadline, and status into one working view.", "This is the table a committee wants before review: organized, current, and tied to the materials being evaluated.", "Cola de revisión", "Esta página organiza postulaciones que necesitan revisión, seguimiento o atención del comité.", "Reúne preparación, prioridad, revisor asignado, fecha y estado en una sola vista de trabajo.", "Es la tabla que un comité necesita antes de revisar: organizada, actual y conectada a los materiales evaluados."],
  ["/shortlist/", "Shortlist", "institution", "This page gathers submissions that have moved into closer decision-making.", "It keeps stronger candidates, notes, status, reviewer context, and final decision steps together.", "Instead of rebuilding a final list after a meeting, the shortlist keeps the decision trail attached.", "Lista corta", "Esta página reúne postulaciones que avanzaron hacia una decisión más cercana.", "Mantiene candidaturas fuertes, notas, estado, contexto de revisores y pasos finales juntos.", "En vez de reconstruir una lista final después de una reunión, la lista corta conserva el rastro de decisión."],
  ["/committee/", "Committee", "institution", "This page coordinates reviewers, jurors, committee members, and pending actions.", "It helps track who has been invited, who has completed work, and what is still waiting.", "This reduces manual follow-up and makes reviewer progress easier to see.", "Comité", "Esta página coordina revisores, jurados, comité y acciones pendientes.", "Ayuda a ver quién fue invitado, quién completó su parte y qué sigue pendiente.", "Reduce seguimientos manuales y hace más visible el progreso de revisión."],
  ["/messages/", "Messages", "institution", "This page keeps program and review communication close to the work it affects.", "It helps teams avoid losing important context in outside email threads or private notes.", "A note about missing materials or reviewer timing should stay near the related record.", "Mensajes", "Esta página mantiene la comunicación de programas y revisión cerca del trabajo que afecta.", "Ayuda a no perder contexto importante en correos externos o notas privadas.", "Una nota sobre materiales faltantes o tiempos de revisión debe permanecer cerca del registro relacionado."],
  ["/reports/", "Reports", "institution", "This page prepares review activity, outcomes, shortlist decisions, and program records for reporting.", "It helps institutions preserve what happened during a cycle without rebuilding the story later.", "Reports support boards, funders, internal records, and future program planning.", "Informes", "Esta página prepara actividad de revisión, resultados, decisiones de lista corta y registros de programa.", "Ayuda a conservar lo que ocurrió durante un ciclo sin reconstruir la historia después.", "Los informes apoyan juntas, financiadores, registros internos y planeación futura."],
  ["/activity-log/", "Activity Log", "institution", "This page records status changes, review movement, messages, shortlist updates, and report history.", "It helps the institution keep a clear memory of what changed across the review cycle.", "When someone asks why an applicant advanced or when a reviewer completed work, this is where the record lives.", "Registro de actividad", "Esta página registra cambios de estado, movimiento de revisión, mensajes, lista corta e historial de informes.", "Ayuda a mantener una memoria clara de lo que cambió durante el ciclo de revisión.", "Cuando alguien pregunta por qué avanzó una postulación o cuándo terminó un revisor, aquí vive el registro."],
  ["/templates/", "Templates", "institution", "This page stores reusable language, criteria, messages, and review structures.", "It helps teams avoid rewriting the same eligibility language, rubric notes, and reviewer instructions for each program.", "Templates reduce repeated admin while keeping institutional language consistent.", "Plantillas", "Esta página guarda lenguaje, criterios, mensajes y estructuras de revisión reutilizables.", "Ayuda a no reescribir la misma elegibilidad, notas de rúbrica o instrucciones para revisores en cada programa.", "Las plantillas reducen administración repetida y mantienen consistente el lenguaje institucional."],
  ["/settings/", "Workspace Settings", "institution", "This page controls workspace details, preferences, team roles, and review defaults.", "It helps the institution keep the workspace aligned with how its programs and committees operate.", "Settings become useful once several programs, reviewers, and templates need a consistent structure.", "Configuración del espacio", "Esta página controla detalles del espacio, preferencias, roles del equipo y valores de revisión.", "Ayuda a que el espacio siga alineado con la forma en que operan los programas y comités.", "La configuración se vuelve útil cuando varios programas, revisores y plantillas necesitan una estructura consistente."],
  ["/artist-dashboard/", "Overview", "artist", "This page gives the artist a quick read on readiness, applications, opportunities, and deadlines.", "It helps the artist understand what needs attention without digging through folders, portals, and notes.", "For an artist balancing studio work and admin, this is the daily command center.", "Resumen", "Esta página le da al artista una lectura rápida de preparación, aplicaciones, oportunidades y fechas límite.", "Ayuda a saber qué necesita atención sin buscar entre carpetas, portales y notas.", "Para un artista que equilibra estudio y administración, este es el centro diario de trabajo."],
  ["/artist-dashboard/passport/", "Creative Passport", "artist", "This page is the artist's reusable professional record.", "It organizes bios, statements, CV, portfolio context, documents, links, and application answers in one place.", "Update it once, then adapt it for grants, residencies, exhibitions, and open calls.", "Pasaporte Creativo", "Esta página es el registro profesional reutilizable del artista.", "Organiza biografías, statements, CV, contexto de portafolio, documentos, enlaces y respuestas en un lugar.", "Actualízalo una vez y adáptalo para becas, residencias, exposiciones y convocatorias."],
  ["/artist-dashboard/portfolio/", "Portfolio", "artist", "This page organizes selected works, images, project notes, and portfolio materials.", "It helps the artist keep visual work ready for applications without rebuilding image sets from scratch.", "When a call asks for images, captions, dates, materials, and dimensions, this page is the organized reference.", "Portafolio", "Esta página organiza obras seleccionadas, imágenes, notas de proyecto y materiales de portafolio.", "Ayuda a mantener el trabajo visual listo para aplicaciones sin rehacer conjuntos de imágenes desde cero.", "Cuando una convocatoria pide imágenes, descripciones, fechas, materiales y dimensiones, esta página es la referencia organizada."],
  ["/artist-dashboard/opportunities/", "Opportunities", "artist", "This page reviews grants, residencies, exhibitions, and open calls through fit and readiness signals.", "It helps the artist decide what to prepare now, what is missing, and what may not be the best use of time.", "Artists often face too many calls and not enough admin time. This turns search into a clearer preparation plan.", "Oportunidades", "Esta página revisa becas, residencias, exposiciones y convocatorias con señales de afinidad y preparación.", "Ayuda al artista a decidir qué preparar ahora, qué falta y qué quizá no vale el tiempo en este momento.", "Los artistas suelen enfrentar demasiadas convocatorias y poco tiempo administrativo. Esto convierte la búsqueda en un plan más claro."],
  ["/artist-dashboard/applications/", "Applications", "artist", "This page tracks applications from draft to submitted, waiting, review, interview, award, or decline.", "It helps the artist see where each opportunity stands and what still needs action.", "Instead of remembering status across several portals and inbox threads, the artist gets one tracker.", "Aplicaciones", "Esta página rastrea aplicaciones desde borrador hasta enviada, en espera, revisión, entrevista, premio o rechazo.", "Ayuda a ver dónde está cada oportunidad y qué acción sigue pendiente.", "En vez de recordar estados entre varios portales y correos, el artista tiene un solo rastreador."],
  ["/artist-dashboard/collaborators/", "Artist Matches", "artist", "This page previews future peer and collaborator matching by practice and opportunity alignment.", "It helps artists notice people who may share a compatible creative context or application direction.", "For residencies, grants, and collaborative projects, the right peer can matter as much as the right institution.", "Coincidencias de artistas", "Esta página muestra una vista previa de futuras coincidencias entre pares y colaboradores por práctica y oportunidades.", "Ayuda a notar personas con contexto creativo o dirección de aplicación compatible.", "Para residencias, becas y proyectos colaborativos, el par correcto puede importar tanto como la institución correcta."],
  ["/artist-dashboard/calendar/", "Calendar", "artist", "This page organizes deadlines, review dates, application tasks, and follow-up timing.", "It helps the artist avoid deadline drift and plan preparation before materials are due.", "Many opportunities fall apart because the deadline arrives before files and language are ready.", "Calendario", "Esta página organiza fechas límite, revisión, tareas de aplicación y seguimiento.", "Ayuda a evitar que las fechas se escapen y permite preparar materiales con tiempo.", "Muchas oportunidades se pierden porque la fecha llega antes de que archivos y textos estén listos."],
  ["/artist-dashboard/messages/", "Messages", "artist", "This page keeps opportunity and application communication close to the artist's materials.", "It helps prevent important follow-ups from getting lost outside the application workflow.", "A request for a missing document should be connected to the application it affects.", "Mensajes", "Esta página mantiene la comunicación de oportunidades y aplicaciones cerca de los materiales del artista.", "Ayuda a que seguimientos importantes no se pierdan fuera del flujo de aplicación.", "Una solicitud de documento faltante debe estar conectada con la aplicación que afecta."],
  ["/artist-dashboard/funding/", "Funding", "artist", "This page summarizes funding opportunities, possible awards, and application value.", "It helps the artist understand which opportunities could materially support the practice.", "Funding affects studio rent, materials, travel, time, and whether a project can happen.", "Fondos", "Esta página resume oportunidades de financiamiento, posibles premios y valor de aplicación.", "Ayuda a entender qué oportunidades podrían apoyar materialmente la práctica.", "El financiamiento afecta renta de estudio, materiales, viajes, tiempo y si un proyecto puede suceder."],
  ["/artist-dashboard/insights/", "Insights", "artist", "This page turns profile, application, and opportunity activity into readiness signals.", "It helps the artist see what is complete, what is missing, what repeats, and what can be improved.", "Instead of guessing why applications feel heavy, the artist can see where the friction is coming from.", "Insights", "Esta página convierte actividad de perfil, aplicaciones y oportunidades en señales de preparación.", "Ayuda a ver qué está completo, qué falta, qué se repite y qué puede mejorar.", "En vez de adivinar por qué las aplicaciones se sienten pesadas, el artista puede ver de dónde viene la fricción."],
  ["/artist-dashboard/settings/", "Settings", "artist", "This page manages artist workspace preferences, profile settings, and sharing behavior.", "It helps the artist decide what is private, reusable, and ready to share.", "Artists should understand and control how their materials move through a submission workflow.", "Configuración", "Esta página gestiona preferencias del espacio de artista, perfil y comportamiento de uso compartido.", "Ayuda a decidir qué es privado, qué es reutilizable y qué está listo para compartirse.", "Los artistas deben entender y controlar cómo sus materiales se mueven por un flujo de postulación."],
  ["/collaborator-dashboard/", "Collaborator Overview", "collaborator", "This page gives an invited reviewer a focused view of assigned work only.", "It shows deadlines, completion rate, messages, and program context without opening the full institution workspace.", "Institutions can involve outside reviewers without giving them broad workspace access.", "Resumen de colaborador", "Esta página da a un revisor invitado una vista enfocada solo en su trabajo asignado.", "Muestra fechas, avance, mensajes y contexto de programa sin abrir todo el espacio institucional.", "Las instituciones pueden involucrar revisores externos sin dar acceso amplio al espacio completo."],
  ["/collaborator-dashboard/assignments/", "My Assignments", "collaborator", "This page shows only the submissions assigned to the collaborator.", "It keeps the reviewer focused on their own queue and protects broader workspace context.", "A guest juror should see the work they need to review, not every institutional record.", "Mis asignaciones", "Esta página muestra solo las postulaciones asignadas al colaborador.", "Mantiene al revisor enfocado en su propia cola y protege el contexto más amplio del espacio.", "Un jurado invitado debe ver el trabajo que necesita revisar, no todos los registros institucionales."],
  ["/collaborator-dashboard/review-queue/", "Review Queue", "collaborator", "This page is the collaborator's focused queue for assigned reviews.", "It keeps rubric, notes, score, and recommendation controls close to the assigned submission.", "The reviewer gets the context needed to complete the task without navigating the full admin workspace.", "Cola de revisión", "Esta página es la cola enfocada del colaborador para revisiones asignadas.", "Mantiene rúbrica, notas, puntuación y recomendación cerca de la postulación asignada.", "El revisor obtiene el contexto necesario sin navegar todo el espacio administrativo."],
  ["/collaborator-dashboard/guidelines/", "Guidelines", "collaborator", "This page keeps program rubrics and review expectations visible.", "It helps external reviewers evaluate consistently without extra documents or repeated instructions.", "Clear guidelines reduce confusion before a reviewer submits notes or recommendations.", "Guías", "Esta página mantiene visibles rúbricas y expectativas del programa.", "Ayuda a revisores externos a evaluar con consistencia sin documentos extra o instrucciones repetidas.", "Guías claras reducen confusión antes de enviar notas o recomendaciones."],
  ["/collaborator-dashboard/messages/", "Messages", "collaborator", "This page contains messages related to assigned review work.", "It keeps collaborator communication scoped to the assignments they are responsible for.", "The reviewer should see messages needed for the task, not the full institution conversation history.", "Mensajes", "Esta página contiene mensajes relacionados con el trabajo de revisión asignado.", "Mantiene la comunicación del colaborador limitada a sus asignaciones.", "El revisor debe ver los mensajes necesarios para su tarea, no todo el historial institucional."],
  ["/collaborator-dashboard/submitted/", "Submitted Reviews", "collaborator", "This page preserves completed reviews and recommendations.", "It creates a clear reviewer record for submitted work.", "The institution can trace completed reviews without asking reviewers to resend notes.", "Revisiones enviadas", "Esta página conserva revisiones y recomendaciones completadas.", "Crea un registro claro del trabajo enviado por el revisor.", "La institución puede rastrear revisiones completadas sin pedir que se reenvíen notas."],
]

const guides = new Map(rows.map((row) => [row[0], row]))

export function getKleioPageGuide(
  pathname: string | null | undefined,
  locale: string = "en",
): KleioPageGuide | undefined {
  if (!pathname) return undefined
  const normalized = pathname.endsWith("/") ? pathname : `${pathname}/`
  const row = guides.get(normalized)
  if (!row) return undefined

  const [, title, role, description, benefit, realWorld, titleEs, descriptionEs, benefitEs, realWorldEs] = row
  const useSpanish = locale === "es"

  return {
    title: useSpanish ? titleEs : title,
    role,
    description: useSpanish ? descriptionEs : description,
    benefit: useSpanish ? benefitEs : benefit,
    realWorld: useSpanish ? realWorldEs : realWorld,
  }
}
