export type KleioPageGuide = {
  title: string
  role: "artist" | "institution" | "collaborator"
  description: string
  benefit: string
  realWorld: string
}

type GuideRow = [
  path: string,
  title: string,
  role: KleioPageGuide["role"],
  description: string,
  benefit: string,
  realWorld: string,
  titleEs: string,
  descriptionEs: string,
  benefitEs: string,
  realWorldEs: string,
]

const rows: GuideRow[] = [
  ["/signup/artist/", "Artist Signup", "artist", "Artists begin their Creative Passport here by adding the details most applications ask for first.", "The form gives artists a reusable foundation without forcing them to flatten their practice into generic portal language.", "This is the first step toward reducing repeated setup across grants, residencies, exhibitions, and open calls.", "Registro de artista", "Aquí el artista comienza su Pasaporte Creativo con los datos que la mayoría de aplicaciones piden primero.", "El formulario crea una base reutilizable sin obligar al artista a reducir su práctica a lenguaje genérico de portal.", "Es el primer paso para reducir configuración repetida entre becas, residencias, exposiciones y convocatorias."],
  ["/signup/institution/", "Institution Signup", "institution", "Institutions begin their workspace here by defining the organization, program context, and review needs.", "The setup gives the team structure before submissions, reviewers, and decisions spread across separate tools.", "A stronger workspace foundation makes the later review cycle easier to explain, manage, and preserve.", "Registro institucional", "Aquí la institución inicia su espacio definiendo organización, contexto de programa y necesidades de revisión.", "La configuración le da estructura al equipo antes de que postulaciones, revisores y decisiones se dispersen entre herramientas.", "Una base de trabajo más clara facilita explicar, gestionar y conservar el ciclo de revisión."],
  ["/dashboard/", "Overview", "institution", "The overview gives the institution a shared read of the review cycle before anyone opens a single application.", "It shows what is moving, what is blocked, and what needs attention so a team can enter review with context.", "Use it like the first page of a review meeting: where are we, what is late, and what needs action today?", "Resumen", "El resumen le da a la institución una lectura compartida del ciclo antes de abrir una postulación individual.", "Muestra qué avanza, qué está bloqueado y qué requiere atención para entrar a revisión con contexto.", "Úsalo como la primera página de una reunión: dónde estamos, qué va tarde y qué necesita acción hoy."],
  ["/programs/", "Programs & Open Calls", "institution", "Programs keeps open calls, grants, residencies, and exhibition cycles organized as active institutional work.", "It helps the team see each program’s status, deadline, applicants, missing materials, and reviewer coverage before entering records one by one.", "Active calls get one clear board instead of scattered intake folders, calendar reminders, and spreadsheet tabs.", "Programas y convocatorias", "Programas mantiene convocatorias, becas, residencias y ciclos de exposición organizados como trabajo institucional activo.", "Ayuda al equipo a ver estado, fecha límite, postulantes, materiales faltantes y cobertura de revisores antes de entrar registro por registro.", "Las convocatorias activas tienen un tablero claro en vez de carpetas, calendarios y hojas dispersas."],
  ["/programs/new/", "Open Call Creation", "institution", "This page shapes the intake structure before artists submit: public description, materials, questions, rubric, dates, and committee coverage.", "A clear call gives artists better instructions and gives reviewers cleaner information when applications arrive.", "The institution can move from idea to organized intake without building the process manually through forms and email.", "Creación de convocatoria", "Esta página estructura la recepción antes de que artistas postulen: descripción pública, materiales, preguntas, rúbrica, fechas y comité.", "Una convocatoria clara da mejores instrucciones a artistas y mejor información a revisores cuando llegan postulaciones.", "La institución puede pasar de idea a recepción organizada sin construir el proceso manualmente entre formularios y correos."],
  ["/submissions/", "Submissions", "institution", "Submissions is the searchable record of applications received across active programs.", "It helps staff find artists, compare records, check material status, and keep review context close to each submission.", "For teams used to inboxes, PDFs, and spreadsheets, this becomes the organized record of what was received.", "Postulaciones", "Postulaciones es el registro buscable de aplicaciones recibidas en programas activos.", "Ayuda al equipo a encontrar artistas, comparar registros, revisar materiales y mantener el contexto cerca de cada postulación.", "Para equipos acostumbrados a correos, PDFs y hojas, esto se vuelve el registro organizado de lo recibido."],
  ["/artists/", "Artist Records", "institution", "Artist Records keeps applicant materials connected to submissions, program history, and institutional memory.", "It helps the institution understand an artist beyond a single file upload or one isolated application.", "Artist context stays connected between cycles instead of becoming disconnected attachments with no memory.", "Registros de artistas", "Registros de artistas mantiene materiales conectados a postulaciones, historial de programas y memoria institucional.", "Ayuda a la institución a entender al artista más allá de un solo archivo o una aplicación aislada.", "El contexto artístico se mantiene conectado entre ciclos en vez de convertirse en adjuntos sin memoria."],
  ["/review-queue/", "Review Queue", "institution", "Review Queue is the working intake layer for applications that need review, follow-up, or committee attention.", "It makes readiness, missing materials, reviewer assignment, priority, and status visible before the team moves into deeper discussion.", "This is the organized table a committee needs before reviewing: current, comparable, and tied to the materials being evaluated.", "Cola de revisión", "La Cola de revisión es la capa de trabajo para aplicaciones que necesitan revisión, seguimiento o atención del comité.", "Hace visibles preparación, materiales faltantes, revisor asignado, prioridad y estado antes de pasar a discusión profunda.", "Es la tabla organizada que el comité necesita antes de revisar: actual, comparable y conectada a los materiales evaluados."],
  ["/review-room/", "Review Room", "institution", "Review Room gives the committee a calmer place to discuss applicants with enough context to move toward a decision.", "It brings the call, applicant readiness, reviewer progress, discussion needs, shortlist movement, and report path into one editorial workspace.", "Instead of deciding from a spreadsheet, the team can see what matters, what is still unresolved, and what is ready to become part of the record.", "Sala de revisión", "La Sala de revisión le da al comité un espacio más claro para discutir postulantes con suficiente contexto para avanzar hacia una decisión.", "Reúne convocatoria, preparación de postulantes, avance de revisores, puntos de discusión, shortlist y ruta de informe en un espacio editorial.", "En vez de decidir desde una hoja de cálculo, el equipo ve qué importa, qué falta resolver y qué está listo para entrar al registro."],
  ["/shortlist/", "Shortlist", "institution", "Shortlist gathers applicants who are ready for closer decision-making.", "It keeps stronger candidates, committee notes, status, reviewer context, and final steps together as the group narrows.", "Instead of rebuilding a final list after a meeting, the shortlist keeps the decision trail attached.", "Lista corta", "La Lista corta reúne postulantes listos para una decisión más cercana.", "Mantiene candidaturas fuertes, notas del comité, estado, contexto de revisores y pasos finales mientras el grupo se reduce.", "En vez de reconstruir una lista final después de la reunión, la lista corta conserva el rastro de decisión."],
  ["/committee/", "Committee", "institution", "Committee coordinates reviewers, jurors, committee members, and pending actions.", "It helps the institution see who has been invited, who is in progress, who has submitted, and what still needs discussion.", "Reviewer coordination becomes visible instead of living in memory, side messages, and manual follow-up.", "Comité", "Comité coordina revisores, jurados, miembros del comité y acciones pendientes.", "Ayuda a ver quién fue invitado, quién está revisando, quién entregó y qué sigue necesitando conversación.", "La coordinación de revisores se vuelve visible en vez de vivir en memoria, mensajes sueltos y seguimiento manual."],
  ["/messages/", "Messages", "institution", "Messages keeps program and review communication close to the work it affects.", "It prevents material requests, reviewer reminders, and decision notes from being lost outside the review flow.", "A note about missing materials or reviewer timing should stay near the related applicant record.", "Mensajes", "Mensajes mantiene comunicación de programa y revisión cerca del trabajo que afecta.", "Evita que solicitudes de materiales, recordatorios de revisores y notas de decisión se pierdan fuera del flujo.", "Una nota sobre materiales faltantes o tiempos de revisión debe permanecer cerca del registro relacionado."],
  ["/reports/", "Reports", "institution", "Reports turns the review cycle into a clear institutional record.", "It gathers outcomes, shortlist movement, reviewer progress, program context, and decision history without making the team rebuild the story manually.", "Reports support boards, funders, internal records, debriefs, and future program planning.", "Informes", "Informes convierte el ciclo de revisión en un registro institucional claro.", "Reúne resultados, movimiento de shortlist, avance de revisores, contexto de programa e historial de decisión sin reconstruir todo manualmente.", "Los informes apoyan juntas, financiadores, registros internos, cierres de ciclo y planeación futura."],
  ["/activity-log/", "Activity Log", "institution", "Activity Log preserves the sequence of status changes, review movement, messages, and report history.", "It helps the institution answer what changed, when it changed, and why a record moved forward.", "When someone asks why an applicant advanced or when a reviewer completed work, this is where the record lives.", "Registro de actividad", "Registro de actividad conserva la secuencia de cambios de estado, movimiento de revisión, mensajes e historial de informes.", "Ayuda a responder qué cambió, cuándo cambió y por qué un registro avanzó.", "Cuando alguien pregunta por qué avanzó una postulación o cuándo terminó un revisor, aquí vive el registro."],
  ["/templates/", "Templates", "institution", "Templates stores reusable language, criteria, messages, and review structures.", "It helps teams avoid rewriting eligibility language, rubric notes, and reviewer instructions for each program.", "Templates reduce repeated administration while keeping institutional language consistent.", "Plantillas", "Plantillas guarda lenguaje, criterios, mensajes y estructuras de revisión reutilizables.", "Ayuda a no reescribir elegibilidad, notas de rúbrica e instrucciones de revisores para cada programa.", "Las plantillas reducen administración repetida y mantienen consistente el lenguaje institucional."],
  ["/settings/", "Workspace Settings", "institution", "Settings keeps workspace details, preferences, team roles, and review defaults aligned.", "It helps the institution maintain a consistent structure as programs, reviewers, and templates grow.", "Settings matter once multiple calls and committees need the same operating logic.", "Configuración del espacio", "Configuración mantiene alineados detalles del espacio, preferencias, roles del equipo y valores de revisión.", "Ayuda a sostener una estructura consistente mientras crecen programas, revisores y plantillas.", "La configuración importa cuando varias convocatorias y comités necesitan la misma lógica operativa."],
  ["/artist-dashboard/", "Artist Overview", "artist", "The artist overview gives a quick read on passport readiness, applications, opportunities, and deadlines.", "It helps the artist see what needs attention without digging through folders, portals, and notes.", "For an artist balancing studio work and admin, this is the daily command center.", "Resumen de artista", "El resumen de artista da una lectura rápida de preparación, aplicaciones, oportunidades y fechas límite.", "Ayuda a saber qué necesita atención sin buscar entre carpetas, portales y notas.", "Para un artista que equilibra estudio y administración, este es el centro diario de trabajo."],
  ["/artist-dashboard/passport/", "Creative Passport", "artist", "Creative Passport is the artist’s reusable professional record.", "It organizes bios, statements, CV, portfolio context, documents, links, and application answers without removing the artist’s authorship.", "Update it once, then adapt it for grants, residencies, exhibitions, and open calls.", "Pasaporte Creativo", "El Pasaporte Creativo es el registro profesional reutilizable del artista.", "Organiza biografías, statements, CV, contexto de portafolio, documentos, enlaces y respuestas sin quitar autoría al artista.", "Actualízalo una vez y adáptalo para becas, residencias, exposiciones y convocatorias."],
  ["/artist-dashboard/portfolio/", "Portfolio", "artist", "Portfolio keeps selected works, images, project notes, and material details ready for reuse.", "It helps the artist prepare visual materials without rebuilding image sets from scratch for every opportunity.", "When a call asks for images, captions, dates, materials, and dimensions, this is the organized reference.", "Portafolio", "Portafolio mantiene obras seleccionadas, imágenes, notas de proyecto y detalles materiales listos para reutilizar.", "Ayuda a preparar materiales visuales sin rehacer conjuntos de imágenes para cada oportunidad.", "Cuando una convocatoria pide imágenes, descripciones, fechas, materiales y dimensiones, esta es la referencia organizada."],
  ["/artist-dashboard/opportunities/", "Grants & Opportunities", "artist", "Grants & Opportunities helps artists sort calls by fit, readiness, deadline pressure, funding, and missing materials.", "It turns discovery into a preparation plan so the artist can decide what deserves time now and what needs more support first.", "Artists often face too many opportunities and not enough admin time; this view protects attention and improves readiness.", "Becas y oportunidades", "Becas y oportunidades ayuda a ordenar convocatorias por afinidad, preparación, urgencia, fondos y materiales faltantes.", "Convierte búsqueda en plan de preparación para decidir qué merece tiempo ahora y qué necesita más soporte primero.", "Los artistas enfrentan demasiadas oportunidades y poco tiempo administrativo; esta vista protege atención y mejora preparación."],
  ["/artist-dashboard/applications/", "Applications", "artist", "Applications tracks each opportunity from draft through submission, review, interview, award, or decline.", "It helps the artist see where each application stands and what still needs action.", "Instead of remembering status across several portals and inbox threads, the artist gets one tracker.", "Aplicaciones", "Aplicaciones rastrea cada oportunidad desde borrador hasta envío, revisión, entrevista, premio o rechazo.", "Ayuda a ver dónde está cada aplicación y qué acción sigue pendiente.", "En vez de recordar estados entre varios portales y correos, el artista tiene un solo rastreador."],
  ["/artist-dashboard/collaborators/", "Artist Matches", "artist", "Artist Matches previews peer and collaborator discovery by practice and opportunity alignment.", "It helps artists notice people who may share a compatible creative context or application direction.", "For residencies, grants, and collaborative projects, the right peer can matter as much as the right institution.", "Coincidencias de artistas", "Coincidencias de artistas muestra una vista previa de pares y colaboradores por práctica y oportunidad.", "Ayuda a notar personas con contexto creativo o dirección de aplicación compatible.", "Para residencias, becas y colaboraciones, el par correcto puede importar tanto como la institución correcta."],
  ["/artist-dashboard/calendar/", "Calendar", "artist", "Calendar organizes deadlines, review dates, application tasks, and follow-up timing.", "It helps the artist avoid deadline drift and plan preparation before materials are due.", "Many opportunities fall apart because the deadline arrives before files and language are ready.", "Calendario", "Calendario organiza fechas límite, revisión, tareas de aplicación y seguimiento.", "Ayuda a evitar que las fechas se escapen y permite preparar materiales con tiempo.", "Muchas oportunidades se pierden porque la fecha llega antes de que archivos y textos estén listos."],
  ["/artist-dashboard/messages/", "Messages", "artist", "Artist Messages keeps opportunity and application communication close to the materials it affects.", "It helps prevent important follow-ups from getting lost outside the application workflow.", "A request for a missing document should stay connected to the application it affects.", "Mensajes", "Mensajes de artista mantiene comunicación de oportunidades y aplicaciones cerca de los materiales que afecta.", "Ayuda a que seguimientos importantes no se pierdan fuera del flujo de aplicación.", "Una solicitud de documento faltante debe quedarse conectada con la aplicación que afecta."],
  ["/artist-dashboard/funding/", "Funding", "artist", "Funding summarizes opportunity value, possible awards, and application effort.", "It helps the artist understand which opportunities could materially support the practice.", "Funding affects studio rent, materials, travel, time, and whether a project can happen.", "Fondos", "Fondos resume valor de oportunidades, posibles premios y esfuerzo de aplicación.", "Ayuda a entender qué oportunidades podrían apoyar materialmente la práctica.", "El financiamiento afecta renta de estudio, materiales, viajes, tiempo y si un proyecto puede suceder."],
  ["/artist-dashboard/insights/", "Insights", "artist", "Insights turns profile, application, and opportunity activity into readiness signals.", "It helps the artist see what is complete, what is missing, what repeats, and what can be improved.", "Instead of guessing why applications feel heavy, the artist can see where friction is coming from.", "Insights", "Insights convierte actividad de perfil, aplicaciones y oportunidades en señales de preparación.", "Ayuda a ver qué está completo, qué falta, qué se repite y qué puede mejorar.", "En vez de adivinar por qué las aplicaciones pesan, el artista ve de dónde viene la fricción."],
  ["/artist-dashboard/settings/", "Artist Settings", "artist", "Artist Settings manages workspace preferences, profile behavior, and sharing controls.", "It helps the artist decide how materials, visibility, and workspace defaults should behave.", "The artist stays in control of what is saved, shared, submitted, or revised.", "Configuración de artista", "Configuración de artista gestiona preferencias del espacio, comportamiento del perfil y controles de compartir.", "Ayuda a decidir cómo deben funcionar materiales, visibilidad y valores del espacio.", "El artista mantiene control sobre lo que se guarda, comparte, envía o revisa."],
  ["/collaborator-dashboard/", "Collaborator Overview", "collaborator", "Collaborator Overview gives an invited reviewer a focused view of assigned work only.", "It shows what is assigned, what is in review, what has been submitted, and what needs discussion without opening the full institution workspace.", "Institutions can involve outside reviewers without giving them broad workspace access.", "Resumen de colaborador", "El resumen de colaborador da a un revisor invitado una vista enfocada solo en su trabajo asignado.", "Muestra qué está asignado, qué está en revisión, qué fue entregado y qué necesita discusión sin abrir todo el espacio institucional.", "Las instituciones pueden involucrar revisores externos sin dar acceso amplio al espacio completo."],
  ["/collaborator-dashboard/assignments/", "My Assignments", "collaborator", "My Assignments shows only the submissions assigned to the collaborator.", "It keeps the reviewer focused on their own queue and protects broader workspace context.", "A guest juror should see the work they need to review, not every institutional record.", "Mis asignaciones", "Mis asignaciones muestra solo las postulaciones asignadas al colaborador.", "Mantiene al revisor enfocado en su propia cola y protege el contexto amplio del espacio.", "Un jurado invitado debe ver el trabajo que necesita revisar, no todos los registros institucionales."],
  ["/collaborator-dashboard/review-queue/", "Review Queue", "collaborator", "The collaborator Review Queue is a focused workspace for assigned reviews.", "It keeps rubric, notes, score, and recommendation controls close to the submission being reviewed.", "The reviewer gets enough context to complete the task without navigating the full admin workspace.", "Cola de revisión", "La Cola de revisión del colaborador es un espacio enfocado para revisiones asignadas.", "Mantiene rúbrica, notas, puntuación y recomendación cerca de la postulación revisada.", "El revisor obtiene suficiente contexto sin navegar todo el espacio administrativo."],
  ["/collaborator-dashboard/guidelines/", "Guidelines", "collaborator", "Guidelines keeps program rubrics and review expectations visible.", "It helps external reviewers evaluate consistently without extra documents or repeated instructions.", "Clear guidelines reduce confusion before a reviewer submits notes or recommendations.", "Guías", "Guías mantiene visibles rúbricas y expectativas del programa.", "Ayuda a revisores externos a evaluar con consistencia sin documentos extra o instrucciones repetidas.", "Guías claras reducen confusión antes de enviar notas o recomendaciones."],
  ["/collaborator-dashboard/messages/", "Messages", "collaborator", "Collaborator Messages contains communication related to assigned review work.", "It keeps reviewer communication scoped to the assignments they are responsible for.", "The reviewer should see messages needed for the task, not the full institution conversation history.", "Mensajes", "Mensajes de colaborador contiene comunicación relacionada con el trabajo de revisión asignado.", "Mantiene la comunicación del revisor limitada a sus asignaciones.", "El revisor debe ver mensajes necesarios para su tarea, no todo el historial institucional."],
  ["/collaborator-dashboard/submitted/", "Submitted Reviews", "collaborator", "Submitted Reviews preserves completed reviews and recommendations.", "It creates a clear reviewer record for submitted work.", "The institution can trace completed reviews without asking reviewers to resend notes.", "Revisiones enviadas", "Revisiones enviadas conserva revisiones y recomendaciones completadas.", "Crea un registro claro del trabajo enviado por el revisor.", "La institución puede rastrear revisiones completadas sin pedir que se reenvíen notas."],
]

const guides = new Map(rows.map((row) => [row[0], row]))

export function getKleioPageGuide(
  pathname: string | null | undefined,
  locale: string = "en",
): KleioPageGuide | undefined {
  if (!pathname) return undefined
  const normalized = pathname.endsWith("/") ? pathname : `${pathname}/`
  const row = guides.get(normalized)
  if (!row) return undefined

  const [, title, role, description, benefit, realWorld, titleEs, descriptionEs, benefitEs, realWorldEs] = row
  const useSpanish = locale === "es"

  return {
    title: useSpanish ? titleEs : title,
    role,
    description: useSpanish ? descriptionEs : description,
    benefit: useSpanish ? benefitEs : benefit,
    realWorld: useSpanish ? realWorldEs : realWorld,
  }
}
