"use client"

import { useEffect, useMemo, useState } from "react"
import { useRouter } from "next/navigation"
import { Bell, Download, Loader2, Send, UserPlus } from "lucide-react"
import {
  applicationCall,
  assignApplicationReviewer,
  buildApplicationsCsv,
  createInstitutionInvitation,
  loadApplicationMessages,
  loadInstitutionApplications,
  loadInstitutionInvitations,
  loadInstitutionOpenCalls,
  loadNotifications,
  markApplicationMessagesRead,
  markNotificationRead,
  saveApplicationReview,
  saveInstitutionOpenCall,
  sendApplicationMessage,
  updateApplicationStatus,
  type ApplicationMessageRecord,
  type ApplicationRecord,
  type ApplicationStatus,
  type InstitutionInvitationRecord,
  type NotificationRecord,
  type OpenCallRecord,
} from "@/lib/kleio-live-data"
import { loadKleioAccount, searchInstitutionMessengerMembers, type InstitutionMessengerMember } from "@/lib/kleio-supabase"
import { loadInstitutionContext } from "@/lib/kleio-live-data"
import { WorkspacePageHeader } from "@/components/kleio/workspace-page-header"

const card = "rounded-2xl border border-[#E7E1F7] bg-white p-5 shadow-[0_18px_48px_rgba(82,64,130,0.06)]"
const input = "h-10 w-full rounded-xl border border-[#E7E1F7] bg-white px-3 text-sm outline-none focus:border-primary/40"
const textarea = "w-full rounded-xl border border-[#E7E1F7] bg-white px-3 py-2 text-sm outline-none focus:border-primary/40"
const primary = "inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground disabled:opacity-50"
const secondary = "inline-flex h-10 items-center justify-center gap-2 rounded-xl border border-[#D8D0F2] bg-white px-4 text-sm font-semibold text-[#5B4B8A] disabled:opacity-50"

function LiveShell({ title, description, children }: { title: string; description: string; children: React.ReactNode }) {
  return <main className="h-full overflow-y-auto px-6 py-6"><div className="mx-auto max-w-[1180px] space-y-5"><WorkspacePageHeader eyebrow="Authenticated institution workspace" title={title} description={description} />{children}</div></main>
}

function StateNotice({ loading, error, empty }: { loading: boolean; error: string; empty?: string }) {
  if (loading) return <div className={`${card} flex items-center gap-2 text-sm text-muted-foreground`}><Loader2 className="size-4 animate-spin" />Loading institution records…</div>
  if (error) return <div role="alert" className={`${card} border-red-200 text-sm text-red-700`}>{error}</div>
  if (empty) return <div className={`${card} text-sm text-muted-foreground`}>{empty}</div>
  return null
}

function Field({ label, value, onChange, type = "text", multiline = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; multiline?: boolean }) {
  return <label className="grid gap-1.5 text-xs font-semibold text-muted-foreground"><span>{label}</span>{multiline ? <textarea className={textarea} rows={4} value={value} onChange={(event) => onChange(event.target.value)} /> : <input type={type} className={input} value={value} onChange={(event) => onChange(event.target.value)} />}</label>
}

const blankCall = { title: "", opportunity_type: "open_call", summary: "", description: "", location: "", participation_format: "online", opens_at: "", deadline_at: "", notification_date: "", program_start_date: "", program_end_date: "", required_materials: "Artist statement, CV, Portfolio" }

export function LiveInstitutionCalls() {
  const [calls, setCalls] = useState<OpenCallRecord[]>([]); const [form, setForm] = useState(blankCall); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("")
  const refresh = () => loadInstitutionOpenCalls().then(setCalls)
  useEffect(() => { void refresh().catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)) }, [])
  async function save(publish: boolean) { setSaving(true); setError(""); setMessage(""); try { const row = await saveInstitutionOpenCall({ ...form, required_materials: form.required_materials.split(",").map((item) => item.trim()).filter(Boolean), opens_at: form.opens_at || null, deadline_at: form.deadline_at || null, notification_date: form.notification_date || null, program_start_date: form.program_start_date || null, program_end_date: form.program_end_date || null, publish }); setMessage(`${row.title} ${publish ? "published" : "saved as a draft"}.`); setForm(blankCall); await refresh() } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save the open call.") } finally { setSaving(false) } }
  return <LiveShell title="Create an open call" description="Save drafts or publish calls directly to the institution’s Supabase workspace."><StateNotice loading={loading} error={error} /><section className={card}><div className="grid gap-4 md:grid-cols-2"><Field label="Call title" value={form.title} onChange={(v) => setForm((f) => ({ ...f, title: v }))} /><Field label="Opportunity type" value={form.opportunity_type} onChange={(v) => setForm((f) => ({ ...f, opportunity_type: v }))} /><Field label="Location" value={form.location} onChange={(v) => setForm((f) => ({ ...f, location: v }))} /><Field label="Participation format" value={form.participation_format} onChange={(v) => setForm((f) => ({ ...f, participation_format: v }))} /><Field label="Opens" type="date" value={form.opens_at} onChange={(v) => setForm((f) => ({ ...f, opens_at: v }))} /><Field label="Deadline" type="date" value={form.deadline_at} onChange={(v) => setForm((f) => ({ ...f, deadline_at: v }))} /><Field label="Notification date" type="date" value={form.notification_date} onChange={(v) => setForm((f) => ({ ...f, notification_date: v }))} /><Field label="Required materials — comma separated" value={form.required_materials} onChange={(v) => setForm((f) => ({ ...f, required_materials: v }))} /></div><div className="mt-4 grid gap-4"><Field label="Public summary" multiline value={form.summary} onChange={(v) => setForm((f) => ({ ...f, summary: v }))} /><Field label="Full description and eligibility" multiline value={form.description} onChange={(v) => setForm((f) => ({ ...f, description: v }))} /></div><div className="mt-4 flex flex-wrap gap-2"><button className={secondary} disabled={saving || !form.title.trim()} onClick={() => void save(false)}>Save draft</button><button className={primary} disabled={saving || !form.title.trim() || !form.deadline_at} onClick={() => void save(true)}>{saving && <Loader2 className="size-4 animate-spin" />}Publish call</button></div>{message && <p role="status" className="mt-3 text-sm font-medium text-emerald-700">{message}</p>}</section><section className={card}><h2 className="font-serif text-xl font-semibold">Saved calls</h2><div className="mt-4 space-y-3">{calls.length ? calls.map((call) => <article key={call.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#E7E1F7] p-4"><div><p className="font-semibold">{call.title}</p><p className="text-xs text-muted-foreground">{call.status} · Deadline {call.deadline_at || "not set"} · Updated {new Date(call.updated_at).toLocaleString()}</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${call.status === "open" ? "bg-emerald-50 text-emerald-700" : "bg-[#F7F4FF] text-[#5B4B8A]"}`}>{call.status}</span></article>) : <p className="text-sm text-muted-foreground">No open calls have been created yet.</p>}</div></section></LiveShell>
}

type ReviewDraft = { score: string; recommendation: string; internal_notes: string }

function SubmissionCard({ application, reviewers, mode, onChanged }: { application: ApplicationRecord; reviewers: InstitutionMessengerMember[]; mode: "submissions" | "queue" | "room" | "shortlist"; onChanged: () => void }) {
  const call = applicationCall(application); const currentReview = application.reviews?.[0]; const [review, setReview] = useState<ReviewDraft>({ score: currentReview?.score?.toString() || "", recommendation: currentReview?.recommendation || "", internal_notes: currentReview?.internal_notes || "" }); const [status, setStatus] = useState<ApplicationStatus>(application.status); const [reviewerId, setReviewerId] = useState(""); const [dueAt, setDueAt] = useState(""); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("")
  async function persistReview() { setSaving(true); setError(""); try { await saveApplicationReview(application.id, { score: review.score ? Number(review.score) : null, recommendation: review.recommendation, internal_notes: review.internal_notes, review_status: "completed" }); setMessage("Review saved."); onChanged() } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save the review.") } finally { setSaving(false) } }
  async function changeStatus(next: ApplicationStatus) { setSaving(true); setError(""); try { await updateApplicationStatus(application.id, next); setStatus(next); setMessage(`Status updated to ${next.replaceAll("_", " ")}.`); onChanged() } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to update status.") } finally { setSaving(false) } }
  async function assign() { if (!reviewerId) return; setSaving(true); setError(""); try { await assignApplicationReviewer(application.id, reviewerId, dueAt || null); setMessage("Reviewer assigned."); onChanged() } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to assign reviewer.") } finally { setSaving(false) } }
  return <article className={card}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-[#A997E8]">{call?.title || "Open call"}</p><h2 className="mt-1 font-serif text-xl font-semibold">{application.artist_name}</h2><p className="text-sm text-muted-foreground">{application.artist_email} · Submitted {application.submitted_at ? new Date(application.submitted_at).toLocaleString() : "—"}</p></div><span className="rounded-full bg-[#F7F4FF] px-3 py-1 text-xs font-semibold capitalize text-[#5B4B8A]">{status.replaceAll("_", " ")}</span></div>
    {(mode === "queue" || mode === "room") && <div className="mt-4 grid gap-4 border-t border-[#E7E1F7] pt-4 lg:grid-cols-2"><div><p className="text-xs font-semibold text-muted-foreground">Reviewer assignment</p><div className="mt-2 flex flex-wrap gap-2"><select className={`${input} min-w-52 flex-1`} value={reviewerId} onChange={(event) => setReviewerId(event.target.value)}><option value="">Select reviewer</option>{reviewers.map((reviewer) => <option key={reviewer.user_id} value={reviewer.user_id}>{reviewer.display_name} — {reviewer.institution_role}</option>)}</select><input className={`${input} w-auto`} type="date" value={dueAt} onChange={(event) => setDueAt(event.target.value)} /><button className={secondary} disabled={saving || !reviewerId} onClick={() => void assign()}>Assign</button></div></div><div><p className="text-xs font-semibold text-muted-foreground">Score and recommendation</p><div className="mt-2 grid gap-2 sm:grid-cols-[100px_1fr]"><input className={input} type="number" min="0" max="100" value={review.score} onChange={(event) => setReview((current) => ({ ...current, score: event.target.value }))} placeholder="0–100" /><select className={input} value={review.recommendation} onChange={(event) => setReview((current) => ({ ...current, recommendation: event.target.value }))}><option value="">Recommendation</option><option value="advance">Advance</option><option value="discuss">Discuss</option><option value="decline">Decline</option><option value="abstain">Abstain</option></select></div><textarea className={`${textarea} mt-2`} rows={3} value={review.internal_notes} onChange={(event) => setReview((current) => ({ ...current, internal_notes: event.target.value }))} placeholder="Internal review notes" /><button className={`${primary} mt-2`} disabled={saving} onClick={() => void persistReview()}>Save review</button></div></div>}
    <div className="mt-4 flex flex-wrap gap-2 border-t border-[#E7E1F7] pt-4">{(["in_review", "needs_follow_up", "shortlisted", "finalist", "accepted", "declined"] as ApplicationStatus[]).map((next) => <button key={next} className={status === next ? primary : secondary} disabled={saving || status === next} onClick={() => void changeStatus(next)}>{next.replaceAll("_", " ")}</button>)}</div>{message && <p role="status" className="mt-3 text-sm font-medium text-emerald-700">{message}</p>}{error && <p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}
  </article>
}

export function LiveInstitutionSubmissions({ mode = "submissions" }: { mode?: "submissions" | "queue" | "room" | "shortlist" }) {
  const [applications, setApplications] = useState<ApplicationRecord[]>([]); const [reviewers, setReviewers] = useState<InstitutionMessengerMember[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("")
  const refresh = () => loadInstitutionApplications().then(setApplications)
  useEffect(() => { void Promise.all([refresh(), loadInstitutionContext().then(async (context) => { const account = await loadKleioAccount(); const members = await searchInstitutionMessengerMembers(context.institution_id, ""); if (account) members.unshift({ user_id: account.user.id, display_name: account.profile.display_name || "You", avatar_url: account.profile.avatar_url, institution_role: context.member_role, membership_status: "active", department: null }); setReviewers(members) })]).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)) }, [])
  const visible = useMemo(() => mode === "shortlist" ? applications.filter((item) => ["shortlisted", "finalist", "accepted"].includes(item.status)) : mode === "queue" ? applications.filter((item) => ["submitted", "in_review", "needs_follow_up"].includes(item.status)) : applications, [applications, mode])
  const titles = { submissions: ["Applicant submissions", "Submitted applications for the institution’s own calls."], queue: ["Review queue", "Assign authenticated institution members, score submissions, and move statuses."], room: ["Review room", "Conduct and persist institutional reviews with decision history."], shortlist: ["Shortlist", "Live shortlisted, finalist, and accepted application records."] }
  return <LiveShell title={titles[mode][0]} description={titles[mode][1]}><StateNotice loading={loading} error={error} empty={!loading && !visible.length ? (mode === "shortlist" ? "No applications have reached the shortlist yet." : "No submitted applications are available yet.") : undefined} />{visible.map((application) => <SubmissionCard key={application.id} application={application} reviewers={reviewers} mode={mode} onChanged={() => void refresh()} />)}</LiveShell>
}

export function LiveInstitutionMessages() {
  const [applications, setApplications] = useState<ApplicationRecord[]>([]); const [activeId, setActiveId] = useState(""); const [messages, setMessages] = useState<ApplicationMessageRecord[]>([]); const [draft, setDraft] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("")
  const active = useMemo(() => applications.find((item) => item.id === activeId) ?? applications[0], [applications, activeId])
  useEffect(() => { void loadInstitutionApplications().then((items) => { setApplications(items); setActiveId(items[0]?.id || "") }).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)) }, [])
  useEffect(() => { if (!active) return; void Promise.all([loadApplicationMessages(active.id), markApplicationMessagesRead(active.id)]).then(([items]) => setMessages(items)).catch((reason: Error) => setError(reason.message)) }, [active])
  async function send() { if (!active || !draft.trim()) return; try { const row = await sendApplicationMessage(active, draft); setMessages((items) => [...items, row]); setDraft("") } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to send message.") } }
  return <LiveShell title="Applicant messages" description="Persistent messages scoped to applications the institution is authorized to manage."><StateNotice loading={loading} error={error} empty={!loading && !applications.length ? "No submitted applications are available for messaging." : undefined} />{active && <div className="grid gap-4 lg:grid-cols-[320px_1fr]"><aside className={card}>{applications.map((application) => <button key={application.id} onClick={() => setActiveId(application.id)} className={`mb-2 w-full rounded-xl p-3 text-left ${active.id === application.id ? "bg-[#F7F4FF]" : "hover:bg-muted"}`}><span className="block text-sm font-semibold">{application.artist_name}</span><span className="text-xs text-muted-foreground">{applicationCall(application)?.title}</span></button>)}</aside><section className={card}><div className="min-h-64 space-y-3">{messages.length ? messages.map((message) => <div key={message.id} className={`max-w-[82%] rounded-2xl px-4 py-3 text-sm ${message.sender_role === "institution" ? "ml-auto bg-primary text-primary-foreground" : "bg-[#F7F4FF]"}`}><p>{message.body}</p><p className="mt-1 text-[0.65rem] opacity-70">{new Date(message.created_at).toLocaleString()}</p></div>) : <p className="text-sm text-muted-foreground">No messages in this application yet.</p>}</div><div className="mt-4 flex gap-2 border-t border-[#E7E1F7] pt-4"><textarea className={`${textarea} flex-1`} rows={2} value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Write to the applicant…" /><button className={primary} disabled={!draft.trim()} onClick={() => void send()}><Send className="size-4" />Send</button></div></section></div>}</LiveShell>
}

export function LiveInstitutionInvitations() {
  const [items, setItems] = useState<InstitutionInvitationRecord[]>([]); const [email, setEmail] = useState(""); const [role, setRole] = useState("reviewer"); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState("")
  const refresh = () => loadInstitutionInvitations().then(setItems)
  useEffect(() => { void refresh().catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)) }, [])
  async function invite() { setError(""); try { const item = await createInstitutionInvitation(email, role); const base = `${window.location.origin}${process.env.NEXT_PUBLIC_BASE_PATH || ""}/auth/accept-invite/?token=${item.token}`; await navigator.clipboard.writeText(base).catch(() => undefined); setMessage("Invitation created. The secure acceptance link was copied when clipboard access was available."); setEmail(""); await refresh() } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to create invitation.") } }
  return <LiveShell title="Team invitations" description="Create secure, expiring institution invitations and track acceptance status."><StateNotice loading={loading} error={error} /><section className={card}><div className="grid gap-3 sm:grid-cols-[1fr_220px_auto]"><input className={input} type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="colleague@example.com" /><select className={input} value={role} onChange={(event) => setRole(event.target.value)}><option value="reviewer">Reviewer</option><option value="committee_chair">Committee chair</option><option value="program_manager">Program manager</option></select><button className={primary} disabled={!email.includes("@") || !email.includes(".")} onClick={() => void invite()}><UserPlus className="size-4" />Create invite</button></div><p className="mt-3 text-xs text-muted-foreground">KLEIO creates an authenticated acceptance link. Automated outbound email delivery is not configured, so share the copied link directly.</p>{message && <p role="status" className="mt-3 text-sm font-medium text-emerald-700">{message}</p>}</section><section className={card}><h2 className="font-serif text-xl font-semibold">Invitation history</h2><div className="mt-4 space-y-2">{items.length ? items.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#E7E1F7] p-3"><div><p className="text-sm font-semibold">{item.email}</p><p className="text-xs text-muted-foreground">{item.role.replaceAll("_", " ")} · Expires {new Date(item.expires_at).toLocaleString()}</p></div><span className="rounded-full bg-[#F7F4FF] px-3 py-1 text-xs font-semibold capitalize text-[#5B4B8A]">{item.status}</span></div>) : <p className="text-sm text-muted-foreground">No invitations created yet.</p>}</div></section></LiveShell>
}

export function LiveInstitutionReports() {
  const [applications, setApplications] = useState<ApplicationRecord[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("")
  useEffect(() => { void loadInstitutionApplications().then(setApplications).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)) }, [])
  function download() { const csv = buildApplicationsCsv(applications); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `kleio-applications-${new Date().toISOString().slice(0, 10)}.csv`; anchor.click(); URL.revokeObjectURL(url) }
  const counts = useMemo(() => Object.fromEntries((["submitted", "in_review", "shortlisted", "finalist", "accepted", "declined"] as ApplicationStatus[]).map((status) => [status, applications.filter((item) => item.status === status).length])), [applications])
  return <LiveShell title="Reports and export" description="Live counts and a CSV generated from the institution’s authorized application records."><StateNotice loading={loading} error={error} /><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(counts).map(([status, count]) => <div className={card} key={status}><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{status.replaceAll("_", " ")}</p><p className="mt-2 font-serif text-3xl font-semibold">{count}</p></div>)}</section><section className={card}><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-serif text-xl font-semibold">Application export</h2><p className="text-sm text-muted-foreground">Includes artist, call, status, submission date, score, and recommendation.</p></div><button className={primary} disabled={!applications.length} onClick={download}><Download className="size-4" />Download CSV</button></div></section></LiveShell>
}

export function LiveNotificationsPanel() {
  const router = useRouter()
  const [items, setItems] = useState<NotificationRecord[]>([]); const [open, setOpen] = useState(false); const [error, setError] = useState("")
  const refresh = () => loadNotifications().then(setItems)
  useEffect(() => { void refresh().catch((reason: Error) => setError(reason.message)); const id = window.setInterval(() => void refresh().catch(() => undefined), 30000); return () => window.clearInterval(id) }, [])
  const unread = items.filter((item) => !item.read_at).length
  async function mark(item: NotificationRecord) { if (!item.read_at) { await markNotificationRead(item.id); await refresh() } if (item.href) router.push(item.href) }
  return <div className="relative"><button type="button" onClick={() => setOpen((value) => !value)} className="relative grid size-10 place-items-center rounded-xl border border-border bg-card text-muted-foreground shadow-sm"><Bell className="size-4" />{unread > 0 && <span className="absolute -right-1 -top-1 grid size-5 place-items-center rounded-full bg-primary text-[0.65rem] font-semibold text-primary-foreground">{unread}</span>}</button>{open && <div className="absolute right-0 top-12 z-50 w-96 rounded-2xl border border-border bg-white p-3 shadow-xl"><p className="px-2 py-1 text-sm font-semibold">Notifications</p>{error && <p className="p-2 text-xs text-red-700">{error}</p>}<div className="max-h-80 overflow-y-auto">{items.length ? items.map((item) => <button key={item.id} onClick={() => void mark(item)} className={`mt-1 block w-full rounded-xl p-3 text-left hover:bg-[#F7F4FF] ${item.read_at ? "opacity-60" : ""}`}><span className="flex items-center gap-2 text-sm font-semibold">{!item.read_at && <span className="size-2 rounded-full bg-primary" />}{item.title}</span><span className="mt-1 block text-xs text-muted-foreground">{item.body}</span><span className="mt-1 block text-[0.65rem] text-muted-foreground">{new Date(item.created_at).toLocaleString()}</span></button>) : <p className="p-3 text-sm text-muted-foreground">No notifications yet.</p>}</div></div>}</div>
}
