begin;

insert into public.opportunity_sources (
  slug, name, base_domain, source_type, ingestion_method, license,
  commercial_reuse_allowed, attribution_required, terms_url,
  update_frequency, active, terms_reviewed_at
)
values
  ('spain-culture-bdns','Spain Ministry of Culture / BDNS','cultura.gob.es','official_api','manual','Official Spanish government publications and the public BDNS/SNPSAP data service. Source attribution is retained; automated reuse is not yet activated in KLEIO.',null,true,'https://www.infosubvenciones.es/bdnstrans/GE/es/ayudaEstado','weekly_review',true,now()),
  ('mexico-cultura','Mexico Secretaría de Cultura','cultura.gob.mx','manual_curation','manual','Official cultural opportunity pages published by the Government of Mexico. Each record retains its official source and review date.',null,true,'https://convocatorias.cultura.gob.mx/','weekly_review',true,now()),
  ('mexico-sic-open-data','Mexico Cultural Information System Open Data','datos.gob.mx','official_api','csv','Creative Commons Attribution 4.0. The available directory export was last updated in 2025 and remains inactive until a current feed can be verified.',true,true,'https://datos.gob.mx/','pending_source_refresh',false,now()),
  ('ibermusicas','Ibermúsicas','ibermusicas.org','manual_curation','manual','Official Ibermúsicas program pages and 2026 call guidelines. Country participation varies by call and applicants must confirm the official guidelines.',null,true,'https://www.ibermusicas.org/index.php/convocatorias/','weekly_review',true,now())
on conflict (slug) do update set
  name=excluded.name, base_domain=excluded.base_domain, source_type=excluded.source_type,
  ingestion_method=excluded.ingestion_method, license=excluded.license,
  commercial_reuse_allowed=excluded.commercial_reuse_allowed,
  attribution_required=excluded.attribution_required, terms_url=excluded.terms_url,
  update_frequency=excluded.update_frequency, active=excluded.active,
  terms_reviewed_at=excluded.terms_reviewed_at, updated_at=now();

with records as (
  select * from (values
    ('spain-culture-bdns','spain-icaa-screenwriting-2026','https://www.cultura.gob.es/servicios-a-la-ciudadania/catalogo/general/05/051860/ficha/051860-2026.html','https://www.cultura.gob.es/servicios-a-la-ciudadania/catalogo/general/05/051860/ficha/051860-2026.html','https://www.cultura.gob.es/servicios-a-la-ciudadania/catalogo/general/05/051860/ficha/051860-2026.html','Ayudas para la escritura de guiones de largometrajes cinematográficos — 2026','Instituto de la Cinematografía y de las Artes Audiovisuales / Ministerio de Cultura','grant','Ayudas para fomentar el desarrollo de guiones de calidad e incentivar a las autoras y los autores de largometrajes. Convocatoria oficial abierta hasta el 23 de julio de 2026 a las 14:00, hora peninsular.','La convocatoria financia el desarrollo de guiones para películas de largometraje. La página oficial contiene las bases, documentación, formularios y acceso a la sede electrónica.',array['Film','Screenwriting','Audiovisual','Literature'],array['individual_artist'],array['Spain'],array['Spain'],array['writer','screenwriter','filmmaker'],null::numeric,null::numeric,'EUR',null::numeric,'2026-07-23 14:00:00+02'::timestamptz,'Europe/Madrid','2026-07-03 00:00:00+02'::timestamptz,false,null::boolean,null::boolean,null::boolean,null::boolean,array['Spanish'],array[]::text[],array[]::text[],'',array[]::text[],'online',array['Spain'],'external','open','official_source','2026-05-26 00:00:00+02'::timestamptz),
    ('spain-culture-bdns','spain-icaa-feature-production-905549','https://www.cultura.gob.es/servicios-a-la-ciudadania/catalogo/general/20/202995/ficha/202995-2026.html','https://www.cultura.gob.es/servicios-a-la-ciudadania/catalogo/general/20/202995/ficha/202995-2026.html','https://www.boe.es/buscar/doc.php?id=BOE-B-2026-15551','Ayudas generales para la producción de largometrajes sobre proyecto — 2º procedimiento 2026','Instituto de la Cinematografía y de las Artes Audiovisuales / Ministerio de Cultura','grant','Convocatoria competitiva para financiar proyectos de largometraje. El segundo procedimiento permanece abierto hasta el 15 de septiembre de 2026 a las 14:00, hora peninsular.','La convocatoria oficial reserva financiación para proyectos de largometraje y establece requisitos para empresas productoras, coproducciones, nacionalidad española del proyecto, gasto en España, accesibilidad y sostenibilidad.',array['Film','Audiovisual','Animation','Media Arts'],array['business','organization'],array['Spain'],array['Spain'],array[]::text[],null::numeric,1000000::numeric,'EUR',null::numeric,'2026-09-15 14:00:00+02'::timestamptz,'Europe/Madrid','2026-06-08 00:00:00+02'::timestamptz,false,null::boolean,null::boolean,null::boolean,null::boolean,array[]::text[],array[]::text[],array['film_production_company'],'Projects must satisfy the official Spanish film-nationality, cultural, expenditure, accessibility, and sustainability requirements.',array[]::text[],'other',array['Spain'],'external','open','official_source','2026-05-13 00:00:00+02'::timestamptz),
    ('spain-culture-bdns','spain-icaa-film-festivals-2026','https://www.cultura.gob.es/servicios-a-la-ciudadania/catalogo/general/05/055040/ficha/055040-2026.html','https://www.cultura.gob.es/servicios-a-la-ciudadania/catalogo/general/05/055040/ficha/055040-2026.html','https://www.cultura.gob.es/servicios-a-la-ciudadania/catalogo/general/05/055040/ficha/055040-2026.html','Ayudas para la participación de películas españolas en festivales — 2026','Instituto de la Cinematografía y de las Artes Audiovisuales / Ministerio de Cultura','grant','Ayudas para apoyar la participación de películas españolas en festivales. La convocatoria oficial permanece abierta hasta el 10 de octubre de 2026.','La página oficial contiene la convocatoria, documentación y resoluciones por periodos. Applicants should confirm the applicable festival period and beneficiary requirements in the official guidelines.',array['Film','Audiovisual','Festivals'],array['business','organization'],array['Spain'],array['Spain'],array[]::text[],null::numeric,null::numeric,'EUR',null::numeric,'2026-10-10 23:59:00+02'::timestamptz,'Europe/Madrid','2026-03-20 00:00:00+01'::timestamptz,false,null::boolean,true,null::boolean,null::boolean,array[]::text[],array[]::text[],array['film_rights_holder_or_representative'],'',array[]::text[],'in_person',array['Spain','International'],'external','open','official_source','2026-03-19 00:00:00+01'::timestamptz),
    ('mexico-cultura','mexico-fonart-gran-premio-2026','https://convocatorias.cultura.gob.mx/vigentes/detalle/4082/li-edicion-del-concurso-gran-premio-nacional-de-arte-popular-2026','https://convocatorias.cultura.gob.mx/vigentes/detalle/4082/li-edicion-del-concurso-gran-premio-nacional-de-arte-popular-2026','https://convocatorias.cultura.gob.mx/vigentes/detalle/4082/li-edicion-del-concurso-gran-premio-nacional-de-arte-popular-2026','LI Edición del Concurso Gran Premio Nacional de Arte Popular 2026','Fondo Nacional para el Fomento de las Artesanías / Secretaría de Cultura','prize_award','Concurso nacional para reconocer obras de arte popular y artesanía mexicana. La fuente oficial informa una bolsa total de premios de MXN 2,775,000; no se presenta como un premio garantizado por participante. Cierra el 14 de agosto de 2026.','Dirigido a personas artesanas del país que elaboran obras con técnicas, saberes, materiales y expresiones culturales tradicionales. Consulta las bases oficiales para categorías, entrega de obra y requisitos documentales.',array['Craft','Folk Art','Textiles','Sculpture','Painting','Cultural Heritage'],array['individual_artist','artisan'],array['Mexico'],array['Mexico'],array['established','emerging'],null::numeric,null::numeric,'MXN',null::numeric,'2026-08-14 23:59:00-06'::timestamptz,'America/Mexico_City','2026-04-13 00:00:00-06'::timestamptz,false,false,true,false,false,array['Spanish'],array[]::text[],array[]::text[],'Participation is limited by the official national and category requirements.',array[]::text[],'in_person',array['Mexico'],'external','open','official_source','2026-04-13 00:00:00-06'::timestamptz),
    ('mexico-cultura','mexico-fonart-grandes-maestros-2026','https://convocatorias.cultura.gob.mx/vigentes/detalle/4081/xiii-edicion-del-concurso-nacional-grandes-maestras-y-maestros-del-patrimonio-artesanal-de-mexico-2026','https://convocatorias.cultura.gob.mx/vigentes/detalle/4081/xiii-edicion-del-concurso-nacional-grandes-maestras-y-maestros-del-patrimonio-artesanal-de-mexico-2026','https://convocatorias.cultura.gob.mx/vigentes/detalle/4081/xiii-edicion-del-concurso-nacional-grandes-maestras-y-maestros-del-patrimonio-artesanal-de-mexico-2026','XIII Edición del Concurso Nacional Grandes Maestras y Maestros del Patrimonio Artesanal de México 2026','Fondo Nacional para el Fomento de las Artesanías / Secretaría de Cultura','prize_award','Concurso nacional para reconocer grandes obras maestras del patrimonio artesanal mexicano. La fuente oficial informa una bolsa total de premios de MXN 1,588,000; no se presenta como un premio garantizado por participante. Cierra el 14 de agosto de 2026.','La convocatoria está dirigida a personas artesanas mexicanas con premios previos específicos. Las obras deben ser recientes y no haber participado en otros certámenes; confirma las categorías y antecedentes admitidos en las bases.',array['Craft','Folk Art','Textiles','Ceramics','Wood','Painting','Cultural Heritage'],array['individual_artist','artisan'],array['Mexico'],array['Mexico'],array['established'],null::numeric,null::numeric,'MXN',null::numeric,'2026-08-14 23:59:00-06'::timestamptz,'America/Mexico_City','2026-04-13 00:00:00-06'::timestamptz,false,false,true,false,false,array['Spanish'],array[]::text[],array[]::text[],'Applicants must meet the prior-award conditions listed in the official call.',array[]::text[],'in_person',array['Mexico'],'external','open','official_source','2026-04-13 00:00:00-06'::timestamptz),
    ('mexico-cultura','mexico-fonart-nacimientos-2026','https://convocatorias.cultura.gob.mx/vigentes/detalle/4083/xxx-edicion-del-concurso-nacional-de-nacimientos-mexicanos-2026','https://convocatorias.cultura.gob.mx/vigentes/detalle/4083/xxx-edicion-del-concurso-nacional-de-nacimientos-mexicanos-2026','https://convocatorias.cultura.gob.mx/vigentes/detalle/4083/xxx-edicion-del-concurso-nacional-de-nacimientos-mexicanos-2026','XXX Edición del Concurso Nacional de Nacimientos Mexicanos 2026','Fondo Nacional para el Fomento de las Artesanías / Secretaría de Cultura','prize_award','Concurso nacional para personas artesanas que elaboran nacimientos mexicanos tradicionales. La fuente oficial informa una bolsa total de premios de MXN 1,075,000; no se presenta como un premio garantizado por participante. Cierra el 25 de septiembre de 2026.','Reconoce la maestría técnica, el uso de saberes y materiales tradicionales, la aportación cultural y estética y la conservación del patrimonio biocultural. Consulta las bases para categorías, entrega de piezas y condiciones.',array['Craft','Folk Art','Ceramics','Textiles','Wood','Metalwork','Painting','Cultural Heritage'],array['individual_artist','artisan'],array['Mexico'],array['Mexico'],array['emerging','established'],null::numeric,null::numeric,'MXN',null::numeric,'2026-09-25 23:59:00-06'::timestamptz,'America/Mexico_City','2026-04-13 00:00:00-06'::timestamptz,false,false,true,false,false,array['Spanish'],array[]::text[],array[]::text[],'Participation is limited to people practicing the eligible Mexican craft traditions and categories in the official call.',array[]::text[],'in_person',array['Mexico'],'external','open','official_source','2026-04-13 00:00:00-06'::timestamptz),
    ('mexico-cultura','mexico-carlos-fuentes-2026','https://convocatorias.cultura.gob.mx/vigentes/detalle/4101/carlos-fuentes-a-la-creacion-literaria-idioma-espanol-2026','https://convocatorias.cultura.gob.mx/vigentes/detalle/4101/carlos-fuentes-a-la-creacion-literaria-idioma-espanol-2026','https://convocatorias.cultura.gob.mx/vigentes/detalle/4101/carlos-fuentes-a-la-creacion-literaria-idioma-espanol-2026','Premio Internacional Carlos Fuentes a la Creación Literaria en el Idioma Español 2026','Secretaría de Cultura de México / Universidad Nacional Autónoma de México','prize_award','Premio internacional para reconocer una trayectoria literaria en español. Las candidaturas deben ser presentadas por instituciones habilitadas y cierran el 14 de agosto de 2026.','No es una autopostulación individual. Ministerios, academias e instituciones educativas o culturales vinculadas con la literatura en español pueden proponer candidaturas conforme a las bases oficiales.',array['Literature','Writing','Spanish-language literature'],array['organization','educational_institution','government'],array['Argentina','Bolivia','Chile','Colombia','Costa Rica','Cuba','Dominican Republic','Ecuador','El Salvador','Equatorial Guinea','Guatemala','Honduras','Mexico','Nicaragua','Panama','Paraguay','Peru','Puerto Rico','Spain','Uruguay','Venezuela'],array['Ibero-America'],array['established'],null::numeric,null::numeric,'MXN',null::numeric,'2026-08-14 23:59:00-06'::timestamptz,'America/Mexico_City','2026-05-11 00:00:00-06'::timestamptz,false,true,null::boolean,null::boolean,null::boolean,array['Spanish'],array[]::text[],array[]::text[],'Candidates must be proposed by an eligible institution; individuals cannot self-nominate.',array[]::text[],'online',array['Mexico','Ibero-America'],'external','open','official_source','2026-05-11 00:00:00-06'::timestamptz),
    ('ibermusicas','ibermusicas-2026-circulacion','https://www.ibermusicas.org/index.php/convocatorias/','https://www.ibermusicas.org/index.php/inscribete-en-convocatorias-y-concursos-de-ibermusicas/','https://www.ibermusicas.org/index.php/convocatorias/','Ayuda a la circulación de profesionales de la música — Ibermúsicas 2026','Programa Ibermúsicas','grant','Apoyo para la internacionalización de espectáculos y para intercambios de creación, composición, investigación y saberes musicales, con énfasis en costos de pasajes.','Dirigida a profesionales de la música de los países adherentes a la convocatoria. La participación por país debe confirmarse en las bases oficiales. La convocatoria cierra el 1 de octubre de 2026 a las 23:59 del país de la persona postulante.',array['Music','Performance','Research','International Touring'],array['individual_artist'],array['Argentina','Brazil','Chile','Colombia','Costa Rica','Cuba','Ecuador','El Salvador','Spain','Mexico','Panama','Paraguay','Peru','Portugal','Uruguay'],array['Ibero-America'],array['emerging','established'],null::numeric,10000::numeric,'USD',null::numeric,'2026-10-01 23:59:00-04'::timestamptz,'Local time in applicant country','2026-06-15 00:00:00-04'::timestamptz,false,false,true,false,false,array[]::text[],array[]::text[],array[]::text[],'Country adherence and eligible professional categories must be confirmed in the official 2026 guidelines.',array[]::text[],'in_person',array['International','Ibero-America'],'external','open','official_source','2026-06-15 00:00:00-04'::timestamptz),
    ('ibermusicas','ibermusicas-2026-programacion','https://www.ibermusicas.org/index.php/convocatorias/','https://www.ibermusicas.org/index.php/inscribete-en-convocatorias-y-concursos-de-ibermusicas/','https://www.ibermusicas.org/index.php/convocatorias/','Ayuda a la programación musical — Ibermúsicas 2026','Programa Ibermúsicas','grant','Apoyo para festivales, ferias, mercados, salas, escuelas, orquestas, coros y otros espacios que invitan a profesionales de la música de otros países.','La línea apoya costos de circulación vinculados a la programación musical internacional. Cierra el 1 de octubre de 2026 a las 23:59 del país postulante; confirma los países adherentes y requisitos en las bases.',array['Music','Festivals','Programming','Cultural Production'],array['organization','nonprofit','educational_institution'],array['Argentina','Brazil','Chile','Colombia','Costa Rica','Cuba','Ecuador','El Salvador','Spain','Mexico','Panama','Paraguay','Peru','Portugal','Uruguay','Venezuela'],array['Ibero-America'],array[]::text[],null::numeric,null::numeric,'USD',null::numeric,'2026-10-01 23:59:00-04'::timestamptz,'Local time in applicant country','2026-06-15 00:00:00-04'::timestamptz,false,false,true,false,false,array[]::text[],array[]::text[],array[]::text[],'Country adherence varies by call; confirm the official guidelines.',array[]::text[],'in_person',array['International','Ibero-America'],'external','open','official_source','2026-06-15 00:00:00-04'::timestamptz),
    ('ibermusicas','ibermusicas-2026-artistas-residencias','https://www.ibermusicas.org/index.php/convocatorias/','https://www.ibermusicas.org/index.php/inscribete-en-convocatorias-y-concursos-de-ibermusicas/','https://www.ibermusicas.org/index.php/convocatorias/','Ayuda a artistas e investigadores para residencias — Ibermúsicas 2026','Programa Ibermúsicas','residency','Apoyo para artistas, compositoras, grupos e investigadores que desarrollen un trabajo creativo o de investigación con una institución o agrupación anfitriona.','Las residencias deben durar al menos tres semanas y pueden realizarse en cualquier parte del mundo. Cierra el 1 de octubre de 2026 a las 23:59 del país postulante.',array['Music','Residency','Research','Composition'],array['individual_artist'],array['Argentina','Brazil','Chile','Colombia','Costa Rica','Cuba','Ecuador','El Salvador','Spain','Mexico','Panama','Paraguay','Peru','Portugal','Uruguay','Venezuela'],array['Ibero-America'],array['emerging','established'],null::numeric,null::numeric,'USD',null::numeric,'2026-10-01 23:59:00-04'::timestamptz,'Local time in applicant country','2026-06-15 00:00:00-04'::timestamptz,false,false,true,true,false,array[]::text[],array[]::text[],array[]::text[],'Country adherence and host requirements must be confirmed in the official guidelines.',array[]::text[],'in_person',array['International','Ibero-America'],'external','open','official_source','2026-06-15 00:00:00-04'::timestamptz),
    ('ibermusicas','ibermusicas-2026-instituciones-residencias','https://www.ibermusicas.org/index.php/convocatorias/','https://www.ibermusicas.org/index.php/inscribete-en-convocatorias-y-concursos-de-ibermusicas/','https://www.ibermusicas.org/index.php/convocatorias/','Ayuda a instituciones para residencias — Ibermúsicas 2026','Programa Ibermúsicas','residency','Apoyo para instituciones públicas o privadas, organismos y agrupaciones que inviten a profesionales de la música a desarrollar una residencia creativa o de investigación.','La residencia debe tener una duración mínima de tres semanas. Cierra el 1 de octubre de 2026 a las 23:59 del país postulante.',array['Music','Residency','Research','Cultural Institutions'],array['organization','nonprofit','educational_institution'],array['Argentina','Brazil','Chile','Colombia','Costa Rica','Cuba','Ecuador','El Salvador','Spain','Mexico','Panama','Paraguay','Peru','Portugal','Uruguay','Venezuela'],array['Ibero-America'],array[]::text[],null::numeric,null::numeric,'USD',null::numeric,'2026-10-01 23:59:00-04'::timestamptz,'Local time in applicant country','2026-06-15 00:00:00-04'::timestamptz,false,false,true,true,false,array[]::text[],array[]::text[],array[]::text[],'Country adherence and institutional requirements must be confirmed in the official guidelines.',array[]::text[],'in_person',array['International','Ibero-America'],'external','open','official_source','2026-06-15 00:00:00-04'::timestamptz),
    ('ibermusicas','ibermusicas-2026-especializacion','https://www.ibermusicas.org/index.php/convocatorias/','https://www.ibermusicas.org/index.php/inscribete-en-convocatorias-y-concursos-de-ibermusicas/','https://www.ibermusicas.org/index.php/convocatorias/','Ayuda a la especialización y el perfeccionamiento artístico y técnico — Ibermúsicas 2026','Programa Ibermúsicas','fellowship','Apoyo para estudios avanzados, especialización y perfeccionamiento en ámbitos artísticos, técnicos y profesionales de la música.','El proceso puede realizarse en una institución o de manera particular con maestras y maestros. Cierra el 1 de octubre de 2026 a las 23:59 del país postulante.',array['Music','Professional Development','Technical Training','Education'],array['individual_artist'],array['Argentina','Brazil','Chile','Colombia','Costa Rica','Cuba','Ecuador','El Salvador','Spain','Mexico','Panama','Paraguay','Peru','Portugal','Uruguay','Venezuela'],array['Ibero-America'],array['emerging','established'],null::numeric,null::numeric,'USD',null::numeric,'2026-10-01 23:59:00-04'::timestamptz,'Local time in applicant country','2026-06-15 00:00:00-04'::timestamptz,false,true,true,true,false,array[]::text[],array[]::text[],array[]::text[],'Country adherence and eligible training formats must be confirmed in the official guidelines.',array[]::text[],'other',array['International','Ibero-America'],'external','open','official_source','2026-06-15 00:00:00-04'::timestamptz),
    ('ibermusicas','ibermusicas-2026-proyectos-virtuales','https://www.ibermusicas.org/index.php/convocatorias/','https://www.ibermusicas.org/index.php/inscribete-en-convocatorias-y-concursos-de-ibermusicas/','https://www.ibermusicas.org/index.php/convocatorias/','Ayuda a proyectos virtuales — Ibermúsicas 2026','Programa Ibermúsicas','grant','Apoyo para álbumes, videoclips, transmisiones, colaboraciones, talleres, podcasts y otros proyectos musicales realizados mediante plataformas virtuales.','La convocatoria está destinada a proyectos musicales que utilicen herramientas virtuales como plataforma principal. Cierra el 1 de octubre de 2026 a las 23:59 del país postulante.',array['Music','Digital Media','Recording','Virtual Projects'],array['individual_artist','organization'],array['Argentina','Brazil','Chile','Colombia','Costa Rica','Cuba','Ecuador','El Salvador','Spain','Mexico','Panama','Paraguay','Peru','Portugal','Uruguay','Venezuela'],array['Ibero-America'],array['emerging','established'],null::numeric,null::numeric,'USD',null::numeric,'2026-10-01 23:59:00-04'::timestamptz,'Local time in applicant country','2026-06-15 00:00:00-04'::timestamptz,false,true,false,false,false,array[]::text[],array[]::text[],array[]::text[],'Country adherence and project-format requirements must be confirmed in the official guidelines.',array[]::text[],'online',array['Online','Ibero-America'],'external','open','official_source','2026-06-15 00:00:00-04'::timestamptz),
    ('ibermusicas','ibermusicas-2026-repertorio','https://www.ibermusicas.org/index.php/convocatorias/','https://www.ibermusicas.org/index.php/inscribete-en-convocatorias-y-concursos-de-ibermusicas/','https://www.ibermusicas.org/index.php/convocatorias/','Ayuda a la promoción del repertorio iberoamericano — Ibermúsicas 2026','Programa Ibermúsicas','grant','Apoyo para grabaciones de alta calidad de obras incluidas en el Catálogo Iberoamericano de Partituras.','Dirigida a orquestas, coros, ensambles y otras formaciones interesadas en interpretar y difundir repertorio iberoamericano. Cierra el 1 de octubre de 2026 a las 23:59 del país postulante.',array['Music','Composition','Recording','Orchestra','Choir'],array['organization','collective'],array['Argentina','Brazil','Chile','Colombia','Costa Rica','Cuba','Ecuador','El Salvador','Spain','Mexico','Panama','Paraguay','Peru','Portugal','Uruguay','Venezuela'],array['Ibero-America'],array[]::text[],null::numeric,null::numeric,'USD',null::numeric,'2026-10-01 23:59:00-04'::timestamptz,'Local time in applicant country','2026-06-15 00:00:00-04'::timestamptz,false,true,false,false,false,array[]::text[],array[]::text[],array[]::text[],'Eligible repertoire and country adherence must be confirmed in the official guidelines.',array[]::text[],'online',array['Ibero-America'],'external','open','official_source','2026-06-15 00:00:00-04'::timestamptz),
    ('ibermusicas','ibermusicas-2026-mid-atlantic-arts','https://www.ibermusicas.org/index.php/convocatorias/','https://www.ibermusicas.org/index.php/inscribete-en-convocatorias-y-concursos-de-ibermusicas/','https://www.ibermusicas.org/index.php/convocatorias/','Convocatoria especial Ibermúsicas – Mid Atlantic Arts 2026','Programa Ibermúsicas / Mid Atlantic Arts','grant','Apoyo para la circulación de artistas iberoamericanos en Estados Unidos, con atención especial a costos y procesos de visas de trabajo.','Mid Atlantic Arts también apoya a organizaciones anfitrionas sin fines de lucro en contratación, producción y difusión. Cierra el 1 de octubre de 2026 a las 23:59 del país postulante.',array['Music','International Touring','Performance'],array['individual_artist','collective'],array['Argentina','Brazil','Chile','Colombia','Costa Rica','Cuba','Ecuador','El Salvador','Spain','Mexico','Panama','Paraguay','Peru','Portugal','Uruguay','Venezuela'],array['Ibero-America'],array['emerging','established'],null::numeric,null::numeric,'USD',null::numeric,'2026-10-01 23:59:00-04'::timestamptz,'Local time in applicant country','2026-06-15 00:00:00-04'::timestamptz,false,false,true,false,false,array[]::text[],array[]::text[],array[]::text[],'Host, visa, routing and country-adherence requirements must be confirmed in the official guidelines.',array[]::text[],'in_person',array['United States','Ibero-America'],'external','open','official_source','2026-06-15 00:00:00-04'::timestamptz),
    ('ibermusicas','ibermusicas-2026-emilia-romagna','https://www.ibermusicas.org/index.php/convocatorias/','https://www.ibermusicas.org/index.php/inscribete-en-convocatorias-y-concursos-de-ibermusicas/','https://www.ibermusicas.org/index.php/convocatorias/','Convocatoria especial Ibermúsicas – Emilia-Romagna 2026','Programa Ibermúsicas / Emilia-Romagna / Fundación ATER','grant','Apoyo para proyectos musicales binacionales y colaborativos entre Iberoamérica y Emilia-Romagna que fortalezcan creación, conciertos e intercambio artístico.','La propuesta requiere una estructura colaborativa entre productoras, instituciones o artistas participantes. Cierra el 1 de octubre de 2026 a las 23:59 del país postulante.',array['Music','International Collaboration','Residency','Performance'],array['individual_artist','organization','collective'],array['Argentina','Brazil','Chile','Colombia','Costa Rica','Cuba','Ecuador','El Salvador','Spain','Mexico','Panama','Paraguay','Peru','Portugal','Uruguay','Venezuela'],array['Ibero-America','Emilia-Romagna'],array['emerging','established'],null::numeric,null::numeric,'EUR',null::numeric,'2026-10-01 23:59:00-04'::timestamptz,'Local time in applicant country','2026-06-15 00:00:00-04'::timestamptz,false,false,true,true,false,array[]::text[],array[]::text[],array[]::text[],'Partner, residency and country-adherence requirements must be confirmed in the official guidelines.',array[]::text[],'in_person',array['Italy','Ibero-America'],'external','open','official_source','2026-06-15 00:00:00-04'::timestamptz),
    ('ibermusicas','ibermusicas-2026-arts-council-england','https://www.ibermusicas.org/index.php/la-nueva-convocatoria-especial-ibermusicas-arts-council-england-permanecera-abierta-hasta-el-31-de-julio/','https://www.ibermusicas.org/index.php/inscribete-en-convocatorias-y-concursos-de-ibermusicas/','https://www.ibermusicas.org/index.php/convocatorias/','Convocatoria especial Ibermúsicas – Arts Council England 2026','Programa Ibermúsicas / Arts Council England','grant','Apoyo para artistas y proyectos musicales iberoamericanos que participen en un circuito de actuaciones e intercambio en Inglaterra durante 2027.','La iniciativa se articula con LatinoLife y Luma Creations e incluye eventos en Londres y Liverpool. Cierra el 31 de julio de 2026 a las 23:59 del país postulante.',array['Music','International Touring','Performance','Cultural Exchange'],array['individual_artist','collective'],array['Argentina','Brazil','Chile','Colombia','Costa Rica','Cuba','Ecuador','El Salvador','Spain','Mexico','Panama','Paraguay','Peru','Portugal','Uruguay','Venezuela'],array['Ibero-America'],array['emerging','established'],null::numeric,null::numeric,'GBP',null::numeric,'2026-07-31 23:59:00-04'::timestamptz,'Local time in applicant country','2026-06-15 00:00:00-04'::timestamptz,false,false,true,false,false,array[]::text[],array[]::text[],array[]::text[],'Touring, selection and country-adherence requirements must be confirmed in the official guidelines.',array[]::text[],'in_person',array['England','United Kingdom','Ibero-America'],'external','open','official_source','2026-06-15 00:00:00-04'::timestamptz),
    ('ibermusicas','ibermusicas-2026-canciones','https://www.ibermusicas.org/index.php/convocatorias/','https://www.ibermusicas.org/index.php/inscribete-en-convocatorias-y-concursos-de-ibermusicas/','https://www.ibermusicas.org/index.php/convocatorias/','Premio Ibermúsicas a la creación de canciones 2026','Programa Ibermúsicas','prize_award','Premio para la creación de nuevas canciones y el fortalecimiento del repertorio musical iberoamericano.','La participación, formato de la obra, autoría y países adherentes deben confirmarse en las bases oficiales. Cierra el 1 de octubre de 2026 a las 23:59 del país postulante.',array['Music','Songwriting','Composition'],array['individual_artist'],array['Argentina','Brazil','Chile','Colombia','Costa Rica','Cuba','Ecuador','El Salvador','Spain','Mexico','Panama','Paraguay','Peru','Portugal','Uruguay','Venezuela'],array['Ibero-America'],array['emerging','established'],null::numeric,null::numeric,'USD',null::numeric,'2026-10-01 23:59:00-04'::timestamptz,'Local time in applicant country','2026-06-15 00:00:00-04'::timestamptz,false,true,false,false,false,array[]::text[],array[]::text[],array[]::text[],'Authorship, language and country-adherence requirements must be confirmed in the official guidelines.',array[]::text[],'online',array['Ibero-America'],'external','open','official_source','2026-06-15 00:00:00-04'::timestamptz),
    ('ibermusicas','ibermusicas-2026-canciones-infancias','https://www.ibermusicas.org/index.php/convocatorias/','https://www.ibermusicas.org/index.php/inscribete-en-convocatorias-y-concursos-de-ibermusicas/','https://www.ibermusicas.org/index.php/convocatorias/','Premio Ibermúsicas a la creación de canciones para las infancias 2026','Programa Ibermúsicas','prize_award','Premio para canciones creadas en dupla con un enfoque en las infancias, la ecología y el cuidado del ambiente.','La convocatoria invita a explorar las lenguas de los países iberoamericanos y lenguas originarias. Cierra el 1 de octubre de 2026 a las 23:59 del país postulante.',array['Music','Songwriting','Children','Composition'],array['individual_artist'],array['Argentina','Brazil','Chile','Colombia','Costa Rica','Cuba','Ecuador','El Salvador','Spain','Mexico','Panama','Paraguay','Peru','Portugal','Uruguay','Venezuela'],array['Ibero-America'],array['emerging','established'],null::numeric,null::numeric,'USD',null::numeric,'2026-10-01 23:59:00-04'::timestamptz,'Local time in applicant country','2026-06-15 00:00:00-04'::timestamptz,false,true,false,false,false,array[]::text[],array[]::text[],array[]::text[],'Creative-duo, authorship and country-adherence requirements must be confirmed in the official guidelines.',array[]::text[],'online',array['Ibero-America'],'external','open','official_source','2026-06-15 00:00:00-04'::timestamptz),
    ('ibermusicas','ibermusicas-2026-sinfonica','https://www.ibermusicas.org/index.php/convocatorias/','https://www.ibermusicas.org/index.php/inscribete-en-convocatorias-y-concursos-de-ibermusicas/','https://www.ibermusicas.org/index.php/convocatorias/','Premio Ibermúsicas de composición de obra para Orquesta Sinfónica 2026','Programa Ibermúsicas','prize_award','Premio para nuevas obras sinfónicas que amplíen el repertorio contemporáneo iberoamericano.','Las obras ganadoras reciben un premio económico y se promueven estrenos con orquestas de países participantes. Cierra el 1 de octubre de 2026 a las 23:59 del país postulante.',array['Music','Composition','Orchestra','Contemporary Music'],array['individual_artist'],array['Argentina','Brazil','Chile','Colombia','Costa Rica','Cuba','Ecuador','El Salvador','Spain','Mexico','Panama','Paraguay','Peru','Portugal','Uruguay','Venezuela'],array['Ibero-America'],array['emerging','established'],null::numeric,null::numeric,'USD',null::numeric,'2026-10-01 23:59:00-04'::timestamptz,'Local time in applicant country','2026-06-15 00:00:00-04'::timestamptz,false,true,false,false,false,array[]::text[],array[]::text[],array[]::text[],'Score, instrumentation, originality and country-adherence requirements must be confirmed in the official guidelines.',array[]::text[],'online',array['Ibero-America'],'external','open','official_source','2026-06-15 00:00:00-04'::timestamptz)
  ) as r(source_slug,external_id,canonical_url,application_url,guidelines_url,title,provider_name,opportunity_type,summary,description,disciplines,eligible_applicant_types,eligible_countries,eligible_regions,career_stages,award_min,award_max,currency,application_fee,deadline_at,deadline_timezone,opens_at,recurring,remote_allowed,travel_supported,accommodation_supported,fiscal_sponsor_allowed,language_requirements,education_requirements,organization_status_requirements,previous_award_restrictions,required_materials,participation_format,locations,application_mode,status,verification_status,source_published_at)
)
insert into public.opportunities (source_id,external_id,canonical_url,application_url,guidelines_url,title,provider_name,opportunity_type,summary,description,disciplines,eligible_applicant_types,eligible_countries,eligible_regions,career_stages,award_min,award_max,currency,application_fee,deadline_at,deadline_timezone,opens_at,recurring,remote_allowed,travel_supported,accommodation_supported,fiscal_sponsor_allowed,language_requirements,education_requirements,organization_status_requirements,previous_award_restrictions,required_materials,participation_format,locations,application_mode,status,verification_status,source_published_at,source_updated_at,last_verified_at)
select s.id,r.external_id,r.canonical_url,r.application_url,r.guidelines_url,r.title,r.provider_name,r.opportunity_type,r.summary,r.description,r.disciplines,r.eligible_applicant_types,r.eligible_countries,r.eligible_regions,r.career_stages,r.award_min,r.award_max,r.currency,r.application_fee,r.deadline_at,r.deadline_timezone,r.opens_at,r.recurring,r.remote_allowed,r.travel_supported,r.accommodation_supported,r.fiscal_sponsor_allowed,r.language_requirements,r.education_requirements,r.organization_status_requirements,r.previous_award_restrictions,r.required_materials,r.participation_format,r.locations,r.application_mode,r.status,r.verification_status,r.source_published_at,now(),now()
from records r join public.opportunity_sources s on s.slug=r.source_slug
on conflict (source_id,external_id) do update set
  canonical_url=excluded.canonical_url, application_url=excluded.application_url,
  guidelines_url=excluded.guidelines_url, title=excluded.title, provider_name=excluded.provider_name,
  opportunity_type=excluded.opportunity_type, summary=excluded.summary, description=excluded.description,
  disciplines=excluded.disciplines, eligible_applicant_types=excluded.eligible_applicant_types,
  eligible_countries=excluded.eligible_countries, eligible_regions=excluded.eligible_regions,
  career_stages=excluded.career_stages, award_min=excluded.award_min, award_max=excluded.award_max,
  currency=excluded.currency, application_fee=excluded.application_fee,
  deadline_at=excluded.deadline_at, deadline_timezone=excluded.deadline_timezone,
  opens_at=excluded.opens_at, recurring=excluded.recurring, remote_allowed=excluded.remote_allowed,
  travel_supported=excluded.travel_supported, accommodation_supported=excluded.accommodation_supported,
  fiscal_sponsor_allowed=excluded.fiscal_sponsor_allowed,
  language_requirements=excluded.language_requirements, education_requirements=excluded.education_requirements,
  organization_status_requirements=excluded.organization_status_requirements,
  previous_award_restrictions=excluded.previous_award_restrictions,
  required_materials=excluded.required_materials, participation_format=excluded.participation_format,
  locations=excluded.locations, application_mode=excluded.application_mode, status=excluded.status,
  verification_status=excluded.verification_status, source_published_at=excluded.source_published_at,
  source_updated_at=excluded.source_updated_at, last_verified_at=excluded.last_verified_at, updated_at=now();

delete from public.opportunity_eligibility_rules r
using public.opportunities o, public.opportunity_sources s
where r.opportunity_id=o.id and o.source_id=s.id
  and s.slug in ('spain-culture-bdns','mexico-cultura','ibermusicas')
  and r.extraction_method='manual_review';

insert into public.opportunity_eligibility_rules (opportunity_id,rule_type,operator,value,requirement_level,source_text,source_url,source_field,extraction_method,verification_status,last_verified_at,sort_order)
select o.id,x.rule_type,x.operator,x.value,x.requirement_level,x.source_text,o.guidelines_url,x.source_field,'manual_review',x.verification_status,now(),x.sort_order
from public.opportunities o
join public.opportunity_sources s on s.id=o.source_id
join (values
  ('spain-icaa-screenwriting-2026','applicant_type','in','["individual_artist"]'::jsonb,'required','The official call is designed to incentivize authors of feature-film screenplays.','official_call','confirmed',1),
  ('spain-icaa-feature-production-905549','applicant_type','in','["business","organization"]'::jsonb,'required','The BOE identifies eligible independent and non-independent production companies and eligible producer groupings.','boe_beneficiaries','confirmed',1),
  ('spain-icaa-film-festivals-2026','applicant_type','in','["business","organization"]'::jsonb,'required','The official call supports eligible entities representing Spanish films at festivals.','official_call','ambiguous',1),
  ('mexico-fonart-gran-premio-2026','country_of_residence','in','["Mexico"]'::jsonb,'required','The official national call is for people practicing eligible Mexican craft traditions.','official_call','confirmed',1),
  ('mexico-fonart-gran-premio-2026','applicant_type','in','["individual_artist","artisan"]'::jsonb,'required','The official call is directed to individual artisans.','official_call','confirmed',2),
  ('mexico-fonart-grandes-maestros-2026','country_of_residence','in','["Mexico"]'::jsonb,'required','The official national call is for eligible Mexican artisans.','official_call','confirmed',1),
  ('mexico-fonart-grandes-maestros-2026','applicant_type','in','["individual_artist","artisan"]'::jsonb,'required','The official call is directed to individual artisans with specified prior awards.','official_call','confirmed',2),
  ('mexico-fonart-nacimientos-2026','country_of_residence','in','["Mexico"]'::jsonb,'required','The official national call is for artisans in Mexico.','official_call','confirmed',1),
  ('mexico-fonart-nacimientos-2026','applicant_type','in','["individual_artist","artisan"]'::jsonb,'required','The official call is directed to individual artisans who create Mexican nativity scenes.','official_call','confirmed',2),
  ('mexico-carlos-fuentes-2026','applicant_type','in','["organization","educational_institution","government"]'::jsonb,'required','Only eligible ministries, academies, educational institutions, and cultural institutions may submit nominations.','official_call','confirmed',1),
  ('ibermusicas-2026-circulacion','applicant_type','in','["individual_artist"]'::jsonb,'required','The official program describes this line for music professionals, artists, groups, researchers and other music-sector practitioners.','official_2026_guidelines','confirmed',1)
) x(external_id,rule_type,operator,value,requirement_level,source_text,source_field,verification_status,sort_order)
  on x.external_id=o.external_id
where s.slug in ('spain-culture-bdns','mexico-cultura','ibermusicas');

update public.opportunity_source_snapshots snap set is_current=false
from public.opportunities o join public.opportunity_sources s on s.id=o.source_id
where snap.opportunity_id=o.id and snap.is_current
  and s.slug in ('spain-culture-bdns','mexico-cultura','ibermusicas');

insert into public.opportunity_source_snapshots (opportunity_id,source_id,fetched_at,raw_data,checksum,is_current)
select o.id,o.source_id,now(),jsonb_build_object('source_url',o.canonical_url,'application_url',o.application_url,'guidelines_url',o.guidelines_url,'review_method','manual_official_source_review','verified_at',now(),'language','es'),encode(digest(o.external_id||'|'||o.canonical_url||'|'||coalesce(o.deadline_at::text,''),'sha256'),'hex'),true
from public.opportunities o join public.opportunity_sources s on s.id=o.source_id
where s.slug in ('spain-culture-bdns','mexico-cultura','ibermusicas')
  and o.external_id in (
    'spain-icaa-screenwriting-2026','spain-icaa-feature-production-905549','spain-icaa-film-festivals-2026',
    'mexico-fonart-gran-premio-2026','mexico-fonart-grandes-maestros-2026','mexico-fonart-nacimientos-2026','mexico-carlos-fuentes-2026',
    'ibermusicas-2026-circulacion','ibermusicas-2026-programacion','ibermusicas-2026-artistas-residencias','ibermusicas-2026-instituciones-residencias','ibermusicas-2026-especializacion','ibermusicas-2026-proyectos-virtuales','ibermusicas-2026-repertorio','ibermusicas-2026-mid-atlantic-arts','ibermusicas-2026-emilia-romagna','ibermusicas-2026-arts-council-england','ibermusicas-2026-canciones','ibermusicas-2026-canciones-infancias','ibermusicas-2026-sinfonica'
  );

commit;
