create index if not exists application_package_versions_source_version_idx on public.application_package_versions (source_version_id);
create index if not exists application_packages_source_version_idx on public.application_packages (source_version_id);
create index if not exists gmail_drafts_connection_idx on public.gmail_drafts (connection_id);
create index if not exists gmail_drafts_package_idx on public.gmail_drafts (package_id);
create index if not exists gmail_send_attempts_artist_idx on public.gmail_send_attempts (artist_user_id);
create index if not exists gmail_send_attempts_draft_idx on public.gmail_send_attempts (gmail_draft_id);
create index if not exists kleio_audit_events_actor_idx on public.kleio_audit_events (actor_user_id);
create index if not exists kleio_audit_events_opportunity_idx on public.kleio_audit_events (opportunity_id);
create index if not exists kleio_audit_events_package_idx on public.kleio_audit_events (package_id);
create index if not exists kleio_feature_flags_updated_by_idx on public.kleio_feature_flags (updated_by);
create index if not exists candidate_eligibility_document_idx on public.opportunity_candidate_eligibility_rules (document_id);
create index if not exists candidate_eligibility_finding_idx on public.opportunity_candidate_eligibility_rules (finding_id);
create index if not exists candidate_eligibility_opportunity_idx on public.opportunity_candidate_eligibility_rules (opportunity_id);
create index if not exists candidate_eligibility_page_idx on public.opportunity_candidate_eligibility_rules (page_id);
create index if not exists candidate_eligibility_source_version_idx on public.opportunity_candidate_eligibility_rules (source_version_id);
create index if not exists candidate_requirements_document_idx on public.opportunity_candidate_requirements (document_id);
create index if not exists candidate_requirements_finding_idx on public.opportunity_candidate_requirements (finding_id);
create index if not exists candidate_requirements_page_idx on public.opportunity_candidate_requirements (page_id);
create index if not exists candidate_requirements_source_version_idx on public.opportunity_candidate_requirements (source_version_id);
create index if not exists canonical_promotions_candidate_eligibility_idx on public.opportunity_canonical_promotions (candidate_eligibility_rule_id);
create index if not exists canonical_promotions_candidate_requirement_idx on public.opportunity_canonical_promotions (candidate_requirement_id);
create index if not exists canonical_promotions_opportunity_idx on public.opportunity_canonical_promotions (opportunity_id);
create index if not exists canonical_promotions_promoted_by_idx on public.opportunity_canonical_promotions (promoted_by);
create index if not exists canonical_promotions_rolled_back_by_idx on public.opportunity_canonical_promotions (rolled_back_by);
create index if not exists research_conflicts_opportunity_idx on public.opportunity_research_conflicts (opportunity_id);
create index if not exists research_conflicts_resolved_by_idx on public.opportunity_research_conflicts (resolved_by);
create index if not exists research_documents_opportunity_idx on public.opportunity_research_documents (opportunity_id);
create index if not exists research_findings_document_idx on public.opportunity_research_findings (document_id);
create index if not exists research_findings_page_idx on public.opportunity_research_findings (page_id);
create index if not exists research_findings_source_version_idx on public.opportunity_research_findings (source_version_id);
create index if not exists research_jobs_opportunity_idx on public.opportunity_research_jobs (opportunity_id);
create index if not exists research_jobs_source_version_idx on public.opportunity_research_jobs (source_version_id);
create index if not exists research_sessions_latest_job_idx on public.opportunity_research_sessions (latest_job_id);
create index if not exists research_sessions_source_version_idx on public.opportunity_research_sessions (source_version_id);
create index if not exists research_sources_source_version_idx on public.opportunity_research_sources (source_version_id);
create index if not exists source_change_previous_version_idx on public.opportunity_source_change_events (previous_source_version_id);
create index if not exists source_change_current_version_idx on public.opportunity_source_change_events (current_source_version_id);
create index if not exists source_versions_research_source_idx on public.opportunity_source_versions (research_source_id);
create index if not exists source_versions_supersedes_idx on public.opportunity_source_versions (supersedes_id);
create index if not exists portal_assistance_adapter_idx on public.portal_assistance_sessions (adapter_id);
create index if not exists portal_assistance_artist_idx on public.portal_assistance_sessions (artist_user_id);
create index if not exists portal_assistance_package_idx on public.portal_assistance_sessions (package_id);

drop policy if exists "Admins manage feature flags" on public.kleio_feature_flags;
create policy "Admins insert feature flags" on public.kleio_feature_flags for insert to authenticated with check (public.is_kleio_admin());
create policy "Admins update feature flags" on public.kleio_feature_flags for update to authenticated using (public.is_kleio_admin()) with check (public.is_kleio_admin());
create policy "Admins delete feature flags" on public.kleio_feature_flags for delete to authenticated using (public.is_kleio_admin());

drop policy if exists "Admins manage portal adapters" on public.portal_provider_adapters;
create policy "Admins insert portal adapters" on public.portal_provider_adapters for insert to authenticated with check (public.is_kleio_admin());
create policy "Admins update portal adapters" on public.portal_provider_adapters for update to authenticated using (public.is_kleio_admin()) with check (public.is_kleio_admin());
create policy "Admins delete portal adapters" on public.portal_provider_adapters for delete to authenticated using (public.is_kleio_admin());
