begin;

insert into public.opportunity_sources (
  slug, name, base_domain, source_type, ingestion_method, license,
  commercial_reuse_allowed, attribution_required, terms_url,
  update_frequency, active, terms_reviewed_at
)
values
  (
    'singapore-national-arts-council',
    'Singapore National Arts Council',
    'nac.gov.sg',
    'manual_curation',
    'manual',
    'Official Government of Singapore grant and programme pages. KLEIO stores source-linked factual summaries and requires applicants to confirm the current official guidelines.',
    null,
    true,
    'https://www.nac.gov.sg/terms-of-use',
    'weekly_review',
    true,
    now()
  ),
  (
    'misk-art-institute',
    'Misk Art Institute',
    'miskartinstitute.org',
    'manual_curation',
    'manual',
    'Official Misk Art Institute programme pages. All rights remain with the provider; KLEIO retains attribution and links applicants to the official source.',
    false,
    true,
    'https://miskartinstitute.org/en/terms-and-conditions',
    'weekly_review',
    true,
    now()
  ),
  (
    'arab-fund-arts-culture',
    'Arab Fund for Arts and Culture',
    'arabculturefund.org',
    'manual_curation',
    'manual',
    'Official AFAC programme pages and application forms. KLEIO stores concise source-attributed metadata only and directs applicants to the provider application.',
    false,
    true,
    'https://www.arabculturefund.org/',
    'weekly_review',
    true,
    now()
  )
on conflict (slug) do update set
  name = excluded.name,
  base_domain = excluded.base_domain,
  source_type = excluded.source_type,
  ingestion_method = excluded.ingestion_method,
  license = excluded.license,
  commercial_reuse_allowed = excluded.commercial_reuse_allowed,
  attribution_required = excluded.attribution_required,
  terms_url = excluded.terms_url,
  update_frequency = excluded.update_frequency,
  active = excluded.active,
  terms_reviewed_at = excluded.terms_reviewed_at,
  updated_at = now();

insert into public.opportunities (
  source_id, external_id, canonical_url, application_url, guidelines_url,
  title, provider_name, opportunity_type, summary, description,
  disciplines, eligible_applicant_types, eligible_countries, eligible_regions,
  citizenship_requirements, residency_requirements, career_stages,
  award_max, currency, application_fee, deadline_at, deadline_timezone, opens_at,
  recurring, remote_allowed, travel_supported, accommodation_supported,
  language_requirements, required_materials, participation_format, locations,
  application_mode, status, verification_status, last_verified_at,
  funding_display_text, funding_amount_type, funding_source_url, funding_source_note,
  funding_verified_at, submission_method, submission_instructions, source_language
)
select
  source_row.id,
  'singapore-nac-presentation-participation-2026-08',
  'https://www.nac.gov.sg/support/funding-and-schemes/presentation-and-participation-grant/how-and-when-to-apply',
  'https://oursggrants.gov.sg/',
  'https://www.nac.gov.sg/support/funding-and-schemes/presentation-and-participation-grant/overview',
  'Presentation and Participation Grant — August 2026 cycle',
  'Singapore National Arts Council',
  'grant',
  'Funding for music recording, publishing, exhibitions or performances, and festivals or conferences, with physical and digital project formats supported. The current cycle closes 14 August 2026 at 23:59 Singapore time.',
  'The official NAC programme is open to individuals, organisations, and collectives. From 16 April 2026, the general grant cap is S$100,000 per applicant per financial year. Applicants should review the current grant guidelines for the exact Singapore eligibility, accounting, and closure requirements before applying.',
  array['Visual Arts','Performing Arts','Music','Literary Arts','Publishing','Festivals','Multidisciplinary'],
  array['individual_artist','organization','collective'],
  array['Singapore'],
  array['Singapore','Southeast Asia','Asia'],
  array[]::text[],
  array['Confirm the current Singapore applicant eligibility rules in the official NAC grant guidelines.'],
  array['emerging','mid-career','established'],
  100000::numeric,
  'SGD',
  null::numeric,
  '2026-08-14 23:59:00+08'::timestamptz,
  'Asia/Singapore',
  null::timestamptz,
  true,
  true,
  null::boolean,
  null::boolean,
  array['English'],
  array['Application through the OurSG Grants Portal','Current NAC grant guideline requirements','Project and budget information','Supporting materials required by the selected grant category'],
  'hybrid',
  array['Singapore','Online'],
  'external',
  'open',
  'official_source',
  now(),
  'Up to S$100,000 per applicant per financial year',
  'conditional_maximum',
  'https://www.nac.gov.sg/support/funding-and-schemes/presentation-and-participation-grant/overview',
  'The cap is stated by NAC; the actual award depends on assessment and eligible project costs.',
  now(),
  'external_portal',
  'Submit through the OurSG Grants Portal by 23:59 SGT on 14 August 2026. Late and incomplete applications are not accepted.',
  'en'
from public.opportunity_sources source_row
where source_row.slug = 'singapore-national-arts-council'
on conflict (source_id, external_id) do update set
  canonical_url = excluded.canonical_url,
  application_url = excluded.application_url,
  guidelines_url = excluded.guidelines_url,
  title = excluded.title,
  provider_name = excluded.provider_name,
  opportunity_type = excluded.opportunity_type,
  summary = excluded.summary,
  description = excluded.description,
  disciplines = excluded.disciplines,
  eligible_applicant_types = excluded.eligible_applicant_types,
  eligible_countries = excluded.eligible_countries,
  eligible_regions = excluded.eligible_regions,
  citizenship_requirements = excluded.citizenship_requirements,
  residency_requirements = excluded.residency_requirements,
  career_stages = excluded.career_stages,
  award_max = excluded.award_max,
  currency = excluded.currency,
  application_fee = excluded.application_fee,
  deadline_at = excluded.deadline_at,
  deadline_timezone = excluded.deadline_timezone,
  opens_at = excluded.opens_at,
  recurring = excluded.recurring,
  remote_allowed = excluded.remote_allowed,
  travel_supported = excluded.travel_supported,
  accommodation_supported = excluded.accommodation_supported,
  language_requirements = excluded.language_requirements,
  required_materials = excluded.required_materials,
  participation_format = excluded.participation_format,
  locations = excluded.locations,
  application_mode = excluded.application_mode,
  status = excluded.status,
  verification_status = excluded.verification_status,
  last_verified_at = excluded.last_verified_at,
  funding_display_text = excluded.funding_display_text,
  funding_amount_type = excluded.funding_amount_type,
  funding_source_url = excluded.funding_source_url,
  funding_source_note = excluded.funding_source_note,
  funding_verified_at = excluded.funding_verified_at,
  submission_method = excluded.submission_method,
  submission_instructions = excluded.submission_instructions,
  source_language = excluded.source_language,
  updated_at = now();

insert into public.opportunities (
  source_id, external_id, canonical_url, application_url, guidelines_url,
  title, provider_name, opportunity_type, summary, description,
  disciplines, eligible_applicant_types, eligible_countries, eligible_regions,
  citizenship_requirements, residency_requirements, career_stages,
  award_max, currency, application_fee, deadline_at, deadline_timezone, opens_at,
  recurring, remote_allowed, travel_supported, accommodation_supported,
  language_requirements, required_materials, participation_format, locations,
  application_mode, status, verification_status, last_verified_at,
  funding_display_text, funding_amount_type, funding_source_url, funding_source_note,
  funding_verified_at, submission_method, submission_instructions, source_language
)
select
  source_row.id,
  'singapore-nac-map-productions-2026',
  'https://www.nac.gov.sg/support/funding-and-schemes/multicultural-arts-programme-grant/productions',
  'https://oursggrants.gov.sg/',
  'https://www.nac.gov.sg/support/funding-and-schemes/multicultural-arts-programme-grant/productions',
  'Multicultural Arts Programme Grant — Productions',
  'Singapore National Arts Council',
  'grant',
  'Supports original, adapted, or redeveloped multicultural performing, visual, literary, and multidisciplinary productions. Applications close 15 September 2026 at 23:59 Singapore time.',
  'The programme supports Singapore-led multicultural productions lasting up to 24 months, including collaborations with regional or international partners. For collaborations, the lead applicant must be a Singapore citizen or permanent resident; projects involving foreign collaborators must remain anchored and led by Singaporean artists.',
  array['Visual Arts','Performing Arts','Literary Arts','Multidisciplinary','Cultural Heritage'],
  array['individual_artist','organization','collective'],
  array['Singapore'],
  array['Singapore','Southeast Asia','Asia'],
  array['For collaborative proposals, the lead applicant must be a Singapore citizen or permanent resident.'],
  array['Projects involving foreign collaborators must be anchored and led by Singaporean artists.'],
  array['emerging','mid-career','established'],
  500000::numeric,
  'SGD',
  null::numeric,
  '2026-09-15 23:59:00+08'::timestamptz,
  'Asia/Singapore',
  '2026-07-15 00:00:00+08'::timestamptz,
  false,
  false,
  null::boolean,
  null::boolean,
  array['English'],
  array['CVs of the key artistic team','Relevant samples of past work','Application materials required in the current MAP Grant guidelines','Project plan and realistic budget'],
  'hybrid',
  array['Singapore'],
  'external',
  'open',
  'official_source',
  now(),
  'Up to 100% of a realistic budget, capped at S$500,000 per application',
  'conditional_maximum',
  'https://www.nac.gov.sg/support/funding-and-schemes/multicultural-arts-programme-grant/productions',
  'The cap and percentage are stated by NAC; the actual award depends on assessment and eligible costs.',
  now(),
  'external_portal',
  'Submit through the OurSG Grants Portal by 23:59 SGT on 15 September 2026. Late and incomplete applications are not accepted.',
  'en'
from public.opportunity_sources source_row
where source_row.slug = 'singapore-national-arts-council'
on conflict (source_id, external_id) do update set
  canonical_url = excluded.canonical_url,
  application_url = excluded.application_url,
  guidelines_url = excluded.guidelines_url,
  title = excluded.title,
  provider_name = excluded.provider_name,
  opportunity_type = excluded.opportunity_type,
  summary = excluded.summary,
  description = excluded.description,
  disciplines = excluded.disciplines,
  eligible_applicant_types = excluded.eligible_applicant_types,
  eligible_countries = excluded.eligible_countries,
  eligible_regions = excluded.eligible_regions,
  citizenship_requirements = excluded.citizenship_requirements,
  residency_requirements = excluded.residency_requirements,
  career_stages = excluded.career_stages,
  award_max = excluded.award_max,
  currency = excluded.currency,
  application_fee = excluded.application_fee,
  deadline_at = excluded.deadline_at,
  deadline_timezone = excluded.deadline_timezone,
  opens_at = excluded.opens_at,
  recurring = excluded.recurring,
  remote_allowed = excluded.remote_allowed,
  travel_supported = excluded.travel_supported,
  accommodation_supported = excluded.accommodation_supported,
  language_requirements = excluded.language_requirements,
  required_materials = excluded.required_materials,
  participation_format = excluded.participation_format,
  locations = excluded.locations,
  application_mode = excluded.application_mode,
  status = excluded.status,
  verification_status = excluded.verification_status,
  last_verified_at = excluded.last_verified_at,
  funding_display_text = excluded.funding_display_text,
  funding_amount_type = excluded.funding_amount_type,
  funding_source_url = excluded.funding_source_url,
  funding_source_note = excluded.funding_source_note,
  funding_verified_at = excluded.funding_verified_at,
  submission_method = excluded.submission_method,
  submission_instructions = excluded.submission_instructions,
  source_language = excluded.source_language,
  updated_at = now();

insert into public.opportunities (
  source_id, external_id, canonical_url, application_url, guidelines_url,
  title, provider_name, opportunity_type, summary, description,
  disciplines, eligible_applicant_types, eligible_countries, eligible_regions,
  citizenship_requirements, residency_requirements, career_stages,
  award_min, award_max, currency, application_fee, deadline_at, deadline_timezone, opens_at,
  recurring, remote_allowed, travel_supported, accommodation_supported,
  language_requirements, required_materials, participation_format, locations,
  application_mode, status, verification_status, last_verified_at,
  funding_display_text, funding_amount_type, funding_source_url, funding_source_note,
  funding_verified_at, submission_method, submission_instructions, source_language
)
select
  source_row.id,
  'singapore-nac-cultural-fellowship-2026',
  'https://www.nac.gov.sg/support/capability-development/nac-cultural-fellowship',
  'https://go.gov.sg/nacculturalfellowship-2026',
  'https://www.nac.gov.sg/support/capability-development/nac-cultural-fellowship',
  'NAC Cultural Fellowship 2026',
  'Singapore National Arts Council',
  'fellowship',
  'A six-month artistic leadership development programme for a small cohort of experienced Singapore practitioners, running October 2026 through March 2027. Applications close 7 August 2026 at 17:00 Singapore time.',
  'The fellowship is designed for artistic directors and associate artists with a substantive professional body of work and demonstrated local and international presence. It includes coaching, cohort learning, studio conversations, and an optional international learning visit. Performing arts practitioners are especially suited, while multidisciplinary artists may also apply.',
  array['Performing Arts','Multidisciplinary','Artistic Leadership','Professional Development'],
  array['individual_artist'],
  array['Singapore'],
  array['Singapore','Southeast Asia','Asia'],
  array['Applicant must be a Singapore citizen or permanent resident.'],
  array['Applicant must be available for the first in-person session on 26 and 27 October 2026.'],
  array['mid-career','established'],
  null::numeric,
  null::numeric,
  null::text,
  null::numeric,
  '2026-08-07 17:00:00+08'::timestamptz,
  'Asia/Singapore',
  null::timestamptz,
  false,
  false,
  true,
  null::boolean,
  array['English'],
  array['Curriculum Vitae covering professional background, milestones, commissioned work, and international engagements','Personal statement of 300 to 500 words addressing the official prompts'],
  'hybrid',
  array['Singapore','International learning visit'],
  'external',
  'open',
  'official_source',
  now(),
  'Development programme; no cash award stated on the official call page',
  'not_stated',
  'https://www.nac.gov.sg/support/capability-development/nac-cultural-fellowship',
  'The official page describes programme participation and an optional learning visit but does not state a cash grant.',
  now(),
  'external_portal',
  'Submit the official online form by 17:00 Singapore time on 7 August 2026. Incomplete and late applications are not considered.',
  'en'
from public.opportunity_sources source_row
where source_row.slug = 'singapore-national-arts-council'
on conflict (source_id, external_id) do update set
  canonical_url = excluded.canonical_url,
  application_url = excluded.application_url,
  guidelines_url = excluded.guidelines_url,
  title = excluded.title,
  provider_name = excluded.provider_name,
  opportunity_type = excluded.opportunity_type,
  summary = excluded.summary,
  description = excluded.description,
  disciplines = excluded.disciplines,
  eligible_applicant_types = excluded.eligible_applicant_types,
  eligible_countries = excluded.eligible_countries,
  eligible_regions = excluded.eligible_regions,
  citizenship_requirements = excluded.citizenship_requirements,
  residency_requirements = excluded.residency_requirements,
  career_stages = excluded.career_stages,
  award_min = excluded.award_min,
  award_max = excluded.award_max,
  currency = excluded.currency,
  application_fee = excluded.application_fee,
  deadline_at = excluded.deadline_at,
  deadline_timezone = excluded.deadline_timezone,
  opens_at = excluded.opens_at,
  recurring = excluded.recurring,
  remote_allowed = excluded.remote_allowed,
  travel_supported = excluded.travel_supported,
  accommodation_supported = excluded.accommodation_supported,
  language_requirements = excluded.language_requirements,
  required_materials = excluded.required_materials,
  participation_format = excluded.participation_format,
  locations = excluded.locations,
  application_mode = excluded.application_mode,
  status = excluded.status,
  verification_status = excluded.verification_status,
  last_verified_at = excluded.last_verified_at,
  funding_display_text = excluded.funding_display_text,
  funding_amount_type = excluded.funding_amount_type,
  funding_source_url = excluded.funding_source_url,
  funding_source_note = excluded.funding_source_note,
  funding_verified_at = excluded.funding_verified_at,
  submission_method = excluded.submission_method,
  submission_instructions = excluded.submission_instructions,
  source_language = excluded.source_language,
  updated_at = now();

insert into public.opportunities (
  source_id, external_id, canonical_url, application_url, guidelines_url,
  title, provider_name, opportunity_type, summary, description,
  disciplines, eligible_applicant_types, eligible_countries, eligible_regions,
  citizenship_requirements, residency_requirements, career_stages,
  award_min, award_max, currency, application_fee, deadline_at, deadline_timezone, opens_at,
  recurring, remote_allowed, travel_supported, accommodation_supported,
  language_requirements, organization_status_requirements, previous_award_restrictions,
  required_materials, participation_format, locations,
  application_mode, status, verification_status, last_verified_at,
  funding_display_text, funding_amount_type, funding_source_url, funding_source_note,
  funding_verified_at, submission_method, submission_instructions, source_language
)
select
  source_row.id,
  'misk-art-book-fair-2026',
  'https://miskartinstitute.org/en/exhibitions/art-book-fair-2026',
  'https://miskartinstitute.org/en/exhibitions/art-book-fair-2026',
  'https://miskartinstitute.org/en/exhibitions/art-book-fair-2026',
  'Art Book Fair 2026',
  'Misk Art Institute',
  'open_call',
  'An international open call for publishers, zine makers, artists, designers, illustrators, bookmakers, curators, researchers, and cultural organisations to participate in Misk Art Week in Riyadh. Registration closes 31 August 2026.',
  'The six-day fair focuses on artists books, independent publishing, experimental print production, and contemporary visual culture. Participants must attend in person, manage their own sales, hold publication rights, and maintain sufficient inventory for the full event. The provider lists participation fees of SAR 1,500 for publishers and SAR 800 for zines.',
  array['Visual Arts','Artists Books','Publishing','Illustration','Graphic Design','Printmaking','Zines'],
  array['individual_artist','publisher','organization','collective','researcher'],
  array['Worldwide'],
  array['Global','Saudi Arabia','West Asia','Middle East','Asia'],
  array[]::text[],
  array['In-person participation in Riyadh is required for the full fair from 5 to 10 December 2026.'],
  array['emerging','mid-career','established'],
  null::numeric,
  null::numeric,
  null::text,
  null::numeric,
  '2026-08-31 23:59:00+03'::timestamptz,
  'Asia/Riyadh — source states the date only; confirm the exact closing time',
  '2026-07-09 00:00:00+03'::timestamptz,
  false,
  false,
  null::boolean,
  null::boolean,
  array['English','Arabic'],
  array['Applicants must hold rights to sell and distribute the submitted publications'],
  'Participation fees apply: SAR 1,500 for publishers and SAR 800 for zines.',
  array['Sufficient inventory for the six-day fair','Publishers: at least three to four titles','Zine makers: at least 100 copies per zine title','Artists: at least one book with 100 copies','Clear editorial approach and relevance to contemporary visual culture'],
  'in_person',
  array['Riyadh','Saudi Arabia'],
  'external',
  'open',
  'source_attributed',
  now(),
  'No grant stated; provider participation fees apply',
  'not_stated',
  'https://miskartinstitute.org/en/exhibitions/art-book-fair-2026',
  'The official page presents participation and sales visibility rather than a funding award.',
  now(),
  'external_portal',
  'Apply through the official Misk Art Institute page. The source states a 31 August 2026 deadline but does not publish a closing time; confirm it directly before submission.',
  'en'
from public.opportunity_sources source_row
where source_row.slug = 'misk-art-institute'
on conflict (source_id, external_id) do update set
  canonical_url = excluded.canonical_url,
  application_url = excluded.application_url,
  guidelines_url = excluded.guidelines_url,
  title = excluded.title,
  provider_name = excluded.provider_name,
  opportunity_type = excluded.opportunity_type,
  summary = excluded.summary,
  description = excluded.description,
  disciplines = excluded.disciplines,
  eligible_applicant_types = excluded.eligible_applicant_types,
  eligible_countries = excluded.eligible_countries,
  eligible_regions = excluded.eligible_regions,
  citizenship_requirements = excluded.citizenship_requirements,
  residency_requirements = excluded.residency_requirements,
  career_stages = excluded.career_stages,
  award_min = excluded.award_min,
  award_max = excluded.award_max,
  currency = excluded.currency,
  application_fee = excluded.application_fee,
  deadline_at = excluded.deadline_at,
  deadline_timezone = excluded.deadline_timezone,
  opens_at = excluded.opens_at,
  recurring = excluded.recurring,
  remote_allowed = excluded.remote_allowed,
  travel_supported = excluded.travel_supported,
  accommodation_supported = excluded.accommodation_supported,
  language_requirements = excluded.language_requirements,
  organization_status_requirements = excluded.organization_status_requirements,
  previous_award_restrictions = excluded.previous_award_restrictions,
  required_materials = excluded.required_materials,
  participation_format = excluded.participation_format,
  locations = excluded.locations,
  application_mode = excluded.application_mode,
  status = excluded.status,
  verification_status = excluded.verification_status,
  last_verified_at = excluded.last_verified_at,
  funding_display_text = excluded.funding_display_text,
  funding_amount_type = excluded.funding_amount_type,
  funding_source_url = excluded.funding_source_url,
  funding_source_note = excluded.funding_source_note,
  funding_verified_at = excluded.funding_verified_at,
  submission_method = excluded.submission_method,
  submission_instructions = excluded.submission_instructions,
  source_language = excluded.source_language,
  updated_at = now();

insert into public.opportunities (
  source_id, external_id, canonical_url, application_url, guidelines_url,
  title, provider_name, opportunity_type, summary, description,
  disciplines, eligible_applicant_types, eligible_countries, eligible_regions,
  citizenship_requirements, residency_requirements, career_stages,
  age_min, age_max, award_min, award_max, currency, application_fee,
  deadline_at, deadline_timezone, opens_at,
  recurring, remote_allowed, travel_supported, accommodation_supported,
  language_requirements, previous_award_restrictions, required_materials,
  participation_format, locations,
  application_mode, status, verification_status, last_verified_at,
  funding_display_text, funding_amount_type, funding_source_url, funding_source_note,
  funding_verified_at, submission_method, submission_instructions, source_language
)
select
  source_row.id,
  'afac-women-in-film-iii-2026',
  'https://www.arabculturefund.org/Programs/78',
  'https://www.arabculturefund.org/Programs/78',
  'https://www.arabculturefund.org/Programs/78',
  'Women in Film III: Training Through Practice',
  'Arab Fund for Arts and Culture / Netflix',
  'professional_development',
  'Training and mentorship for early-career Arab women filmmakers residing in Egypt, Jordan, Kuwait, Saudi Arabia, or the United Arab Emirates. The call closes 29 July 2026.',
  'The programme has two tracks: short-film project teams made up of a writer-director and producer, and individual technical applicants in cinematography, editing, or sound design. It combines weekly online sessions with a five-day in-person workshop or residency in the UAE or Saudi Arabia.',
  array['Film','Screenwriting','Producing','Cinematography','Editing','Sound Design'],
  array['individual_artist','project_team'],
  array['Egypt','Jordan','Kuwait','Saudi Arabia','United Arab Emirates'],
  array['North Africa','West Asia','Middle East','Africa','Asia'],
  array['Applicant must be an Arab woman.'],
  array['Applicant must reside in Egypt, Jordan, Kuwait, Saudi Arabia, or the United Arab Emirates.'],
  array['early-career'],
  23,
  30,
  null::numeric,
  null::numeric,
  null::text,
  null::numeric,
  '2026-07-29 23:59:00+03'::timestamptz,
  'Provider local time — source states the date only; confirm the exact closing time',
  '2026-05-18 00:00:00+03'::timestamptz,
  false,
  true,
  null::boolean,
  null::boolean,
  array['English','Arabic'],
  'Applicants may not have a current open AFAC grant and may not have prior full-length feature-film or television-series credits in the listed roles.',
  array['Project teams: story treatment and draft script for a short fiction narrative film','Individual cinematographers, editors, and sound designers: previous project samples','All supporting materials requested by the selected official application form'],
  'hybrid',
  array['Online','United Arab Emirates','Saudi Arabia'],
  'external',
  'open',
  'source_attributed',
  now(),
  'Training, mentorship, and residency participation; no cash award stated',
  'not_stated',
  'https://www.arabculturefund.org/Programs/78',
  'The official programme page describes training and capacity-building rather than a cash grant.',
  now(),
  'external_portal',
  'Choose either the project-team application or the individual technical-track application on the official AFAC page. The provider states a 29 July 2026 deadline but does not publish a closing time on the programme page; confirm it before submission.',
  'en'
from public.opportunity_sources source_row
where source_row.slug = 'arab-fund-arts-culture'
on conflict (source_id, external_id) do update set
  canonical_url = excluded.canonical_url,
  application_url = excluded.application_url,
  guidelines_url = excluded.guidelines_url,
  title = excluded.title,
  provider_name = excluded.provider_name,
  opportunity_type = excluded.opportunity_type,
  summary = excluded.summary,
  description = excluded.description,
  disciplines = excluded.disciplines,
  eligible_applicant_types = excluded.eligible_applicant_types,
  eligible_countries = excluded.eligible_countries,
  eligible_regions = excluded.eligible_regions,
  citizenship_requirements = excluded.citizenship_requirements,
  residency_requirements = excluded.residency_requirements,
  career_stages = excluded.career_stages,
  age_min = excluded.age_min,
  age_max = excluded.age_max,
  award_min = excluded.award_min,
  award_max = excluded.award_max,
  currency = excluded.currency,
  application_fee = excluded.application_fee,
  deadline_at = excluded.deadline_at,
  deadline_timezone = excluded.deadline_timezone,
  opens_at = excluded.opens_at,
  recurring = excluded.recurring,
  remote_allowed = excluded.remote_allowed,
  travel_supported = excluded.travel_supported,
  accommodation_supported = excluded.accommodation_supported,
  language_requirements = excluded.language_requirements,
  previous_award_restrictions = excluded.previous_award_restrictions,
  required_materials = excluded.required_materials,
  participation_format = excluded.participation_format,
  locations = excluded.locations,
  application_mode = excluded.application_mode,
  status = excluded.status,
  verification_status = excluded.verification_status,
  last_verified_at = excluded.last_verified_at,
  funding_display_text = excluded.funding_display_text,
  funding_amount_type = excluded.funding_amount_type,
  funding_source_url = excluded.funding_source_url,
  funding_source_note = excluded.funding_source_note,
  funding_verified_at = excluded.funding_verified_at,
  submission_method = excluded.submission_method,
  submission_instructions = excluded.submission_instructions,
  source_language = excluded.source_language,
  updated_at = now();

-- Replace only the eligibility rules maintained by this migration.
delete from public.opportunity_eligibility_rules rule_row
using public.opportunities opportunity_row
where rule_row.opportunity_id = opportunity_row.id
  and opportunity_row.external_id in (
    'singapore-nac-presentation-participation-2026-08',
    'singapore-nac-map-productions-2026',
    'singapore-nac-cultural-fellowship-2026',
    'misk-art-book-fair-2026',
    'afac-women-in-film-iii-2026'
  );

insert into public.opportunity_eligibility_rules (
  opportunity_id, rule_type, operator, value, requirement_level,
  source_text, source_url, source_field, extraction_method,
  verification_status, last_verified_at, sort_order
)
select
  opportunity_row.id,
  rule_data.rule_type,
  rule_data.operator,
  rule_data.value,
  rule_data.requirement_level,
  rule_data.source_text,
  opportunity_row.canonical_url,
  rule_data.source_field,
  'manual_official_source_review',
  rule_data.verification_status,
  now(),
  rule_data.sort_order
from public.opportunities opportunity_row
join (
  values
    ('singapore-nac-presentation-participation-2026-08','applicant_type','in','["individual_artist","organization","collective"]'::jsonb,'required','The official programme overview states that individuals, organisations, and collectives may apply.','official_programme_overview','confirmed',1),
    ('singapore-nac-presentation-participation-2026-08','country_of_residence','in','["Singapore"]'::jsonb,'review_required','The programme supports arts practice and participation in Singapore; the precise applicant eligibility must be confirmed in the current grant guidelines.','current_grant_guidelines','ambiguous',2),
    ('singapore-nac-map-productions-2026','citizenship','in','["Singapore citizen","Singapore permanent resident"]'::jsonb,'required','For collaborations, the lead applicant must be a Singapore citizen or permanent resident.','official_collaboration_eligibility','confirmed',1),
    ('singapore-nac-map-productions-2026','country_of_residence','in','["Singapore"]'::jsonb,'required','Collaborative projects must be anchored and led by Singaporean artists.','official_collaboration_eligibility','confirmed',2),
    ('singapore-nac-cultural-fellowship-2026','citizenship','in','["Singapore citizen","Singapore permanent resident"]'::jsonb,'required','The official call is applicable to Singapore citizens or permanent residents.','who_is_this_for','confirmed',1),
    ('singapore-nac-cultural-fellowship-2026','career_stage','in','["mid-career","established"]'::jsonb,'required','Applicants need a substantive professional body of work and demonstrated local and international presence.','who_is_this_for','confirmed',2),
    ('misk-art-book-fair-2026','applicant_type','in','["individual_artist","publisher","organization","collective","researcher"]'::jsonb,'required','The call names publishers, zine makers, artists, designers, illustrators, printers, bookmakers, curators, researchers, and cultural organisations or institutions.','who_is_it_for','confirmed',1),
    ('misk-art-book-fair-2026','participation_format','equals','"in_person"'::jsonb,'required','In-person participation is required for the full six-day fair.','participation_requirements','confirmed',2),
    ('afac-women-in-film-iii-2026','country_of_residence','in','["Egypt","Jordan","Kuwait","Saudi Arabia","United Arab Emirates"]'::jsonb,'required','The call is limited to Arab women residents of the five named countries.','who_can_apply','confirmed',1),
    ('afac-women-in-film-iii-2026','age','between','{"min":23,"max":30}'::jsonb,'required','Applicants must be women between 23 and 30 years old.','who_can_apply','confirmed',2),
    ('afac-women-in-film-iii-2026','career_stage','equals','"early-career"'::jsonb,'required','Directors and technical applicants may have worked on no more than one short film outside their studies and may not have full-length feature or TV-series credits in the listed roles.','who_can_apply','confirmed',3)
) as rule_data(external_id,rule_type,operator,value,requirement_level,source_text,source_field,verification_status,sort_order)
  on rule_data.external_id = opportunity_row.external_id;

update public.opportunity_source_snapshots snapshot_row
set is_current = false
from public.opportunities opportunity_row
where snapshot_row.opportunity_id = opportunity_row.id
  and snapshot_row.is_current
  and opportunity_row.external_id in (
    'singapore-nac-presentation-participation-2026-08',
    'singapore-nac-map-productions-2026',
    'singapore-nac-cultural-fellowship-2026',
    'misk-art-book-fair-2026',
    'afac-women-in-film-iii-2026'
  );

insert into public.opportunity_source_snapshots (
  opportunity_id, source_id, fetched_at, raw_data, checksum, is_current
)
select
  opportunity_row.id,
  opportunity_row.source_id,
  now(),
  jsonb_build_object(
    'source_url', opportunity_row.canonical_url,
    'application_url', opportunity_row.application_url,
    'guidelines_url', opportunity_row.guidelines_url,
    'review_method', 'manual_official_source_review',
    'verified_at', now(),
    'deadline_time_note', case
      when opportunity_row.external_id in ('misk-art-book-fair-2026','afac-women-in-film-iii-2026')
        then 'The source states a deadline date without a closing time. KLEIO normalizes the date to 23:59 provider-local time for sorting and tells artists to confirm the exact time.'
      else 'The source states the closing time explicitly.'
    end,
    'language', opportunity_row.source_language
  ),
  encode(digest(
    opportunity_row.external_id || '|' || opportunity_row.canonical_url || '|' || coalesce(opportunity_row.deadline_at::text,''),
    'sha256'
  ), 'hex'),
  true
from public.opportunities opportunity_row
where opportunity_row.external_id in (
  'singapore-nac-presentation-participation-2026-08',
  'singapore-nac-map-productions-2026',
  'singapore-nac-cultural-fellowship-2026',
  'misk-art-book-fair-2026',
  'afac-women-in-film-iii-2026'
);

commit;
