begin;

with reviewed_source as (
  select id
  from public.opportunity_sources
  where slug = 'admin-import'
)
insert into public.opportunities (
  source_id,
  external_id,
  canonical_url,
  application_url,
  guidelines_url,
  title,
  provider_name,
  provider_id,
  opportunity_type,
  summary,
  description,
  disciplines,
  eligible_applicant_types,
  eligible_countries,
  eligible_regions,
  career_stages,
  application_fee,
  deadline_at,
  deadline_timezone,
  recurring,
  remote_allowed,
  travel_supported,
  accommodation_supported,
  required_materials,
  participation_format,
  locations,
  application_mode,
  status,
  verification_status,
  last_verified_at,
  funding_display_text,
  funding_amount_type,
  funding_source_url,
  funding_source_note,
  submission_method,
  submission_email,
  submission_instructions,
  source_language
)
select
  reviewed_source.id,
  'slow-pottery-artist-residency-2026',
  'https://www.slowpottery.com/pages/artist-residencies',
  'https://www.slowpottery.com/pages/artist-residencies',
  'https://www.slowpottery.com/pages/artist-residencies',
  'Slow Pottery Self-Guided Artist Residency 2026',
  'Slow Pottery / Velanga Orchard',
  'slow-pottery',
  'residency',
  'A self-guided residency at Velanga Orchard in Andhra Pradesh, India, open to international artists including ceramic artists. Remaining 2026 dates are offered in August, September, October, and November–December.',
  'Artists develop their own projects in a rural mango-farm setting. Ceramic residents receive access to the Slow Pottery studio, an electric wheel, basic tools, kiln firing, shelves, and up to 100 kg of clay per week. The program is self-funded: the official page lists separate weekly tariffs for ceramic artists that include accommodation and meals. No teaching or technical guidance is included.',
  array['Ceramics','Craft','Sculpture','Painting','Photography','Illustration','Graphic Design','Writing','Movement Arts','Multidisciplinary'],
  array['Individual artists','Ceramic artists','Studio potters','International artists'],
  array['Worldwide'],
  array['Global','India','South Asia','Asia'],
  array['Emerging','Mid-career','Established'],
  null,
  null,
  'Asia/Kolkata',
  true,
  false,
  null,
  true,
  array['Name','Age and nationality','Art or craft','Preferred dates and duration','Equipment requirements','Short artist statement and residency goals'],
  'in_person',
  array['Velanga Orchard','Jambuneradipalli','Andhra Pradesh','India','South Asia','Asia'],
  'external',
  'open',
  'official_source',
  now(),
  'Self-funded. The official page lists ceramic-artist tariffs of INR 45,660 for single occupancy or INR 36,210 for double occupancy for 6 nights / 7 days. Accommodation, meals, studio access, and listed materials are included; applicants should confirm current pricing directly with the host.',
  'not_stated',
  'https://www.slowpottery.com/pages/artist-residencies',
  'This is a paid residency rather than a grant or stipend. The official page states that payment details are provided after email inquiry and offers a two-instalment option.',
  'email',
  'hello@slowpottery.com',
  'Email the host with your name, age and nationality, art form, preferred dates and duration, equipment needs, and a short artist statement describing your goals and expectations.',
  'en'
from reviewed_source
on conflict (source_id, external_id) do update
set canonical_url = excluded.canonical_url,
    application_url = excluded.application_url,
    guidelines_url = excluded.guidelines_url,
    title = excluded.title,
    provider_name = excluded.provider_name,
    provider_id = excluded.provider_id,
    opportunity_type = excluded.opportunity_type,
    summary = excluded.summary,
    description = excluded.description,
    disciplines = excluded.disciplines,
    eligible_applicant_types = excluded.eligible_applicant_types,
    eligible_countries = excluded.eligible_countries,
    eligible_regions = excluded.eligible_regions,
    career_stages = excluded.career_stages,
    application_fee = excluded.application_fee,
    deadline_at = excluded.deadline_at,
    deadline_timezone = excluded.deadline_timezone,
    recurring = excluded.recurring,
    remote_allowed = excluded.remote_allowed,
    travel_supported = excluded.travel_supported,
    accommodation_supported = excluded.accommodation_supported,
    required_materials = excluded.required_materials,
    participation_format = excluded.participation_format,
    locations = excluded.locations,
    application_mode = excluded.application_mode,
    status = excluded.status,
    verification_status = excluded.verification_status,
    last_verified_at = excluded.last_verified_at,
    funding_display_text = excluded.funding_display_text,
    funding_amount_type = excluded.funding_amount_type,
    funding_source_url = excluded.funding_source_url,
    funding_source_note = excluded.funding_source_note,
    submission_method = excluded.submission_method,
    submission_email = excluded.submission_email,
    submission_instructions = excluded.submission_instructions,
    source_language = excluded.source_language,
    updated_at = now();

commit;
